// prescribeWeek.mjs — the ship-to-Shad gate's machine half (directive §14):
// generate N consecutive days for the P0 fixture through every gate, render
// them as food a person can cook, and consolidate the grocery list.
//
//   node scripts/prescribeWeek.mjs            # 14 days → docs/P0_FOURTEEN_DAYS.md
//   node scripts/prescribeWeek.mjs --days=7
//
// The cooking half of the gate belongs to the owner. This script's job is
// that when he opens the file, every number on it is machine-verified and
// every plate is allergen-scanned — and the paper says so.

import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const { qaDbPath, SKIP_NOTE, loadPoolRows, runPersona } = require("../tests/personas/harness.js");
const { PERSONAS } = require("../tests/personas/fixtures.js");
const { classifyStoreSection } = require("../src/lib/groceryList.js");
const { toPurchaseUnits } = require("../src/lib/purchaseUnits.js");

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "../../docs/P0_FOURTEEN_DAYS.md");
const DAYS = Number((process.argv.find((a) => a.startsWith("--days=")) || "").split("=")[1]) || 14;

const db = qaDbPath();
if (!db) { console.error(SKIP_NOTE); process.exit(1); }
const rows = loadPoolRows(db);
const p0 = PERSONAS.find((p) => p.id === "p0");
const run = runPersona(p0, rows, { days: DAYS, seed: 20260819 });

const okDays = run.days.filter((d) => d.ok).length;
const hits = run.days.flatMap((d) => d.scan.hits);
const r0 = (n) => Math.round(n);

const L = [];
L.push(`# ${DAYS} days, prescribed — P0 profile`);
L.push("");
L.push(`Targets: **${typeof p0.targets.kcal === "number" ? p0.targets.kcal : ""} kcal** · protein ${p0.targets.proteinG.lo}–${p0.targets.proteinG.hi} g · fat ${p0.targets.fatG.lo}–${p0.targets.fatG.hi} g · net carbs ${p0.targets.netCarbG.lo}–${p0.targets.netCarbG.hi} g · floor ${p0.targets.floorKcal} kcal.`);
L.push(`Exclusions (allergy-hard): ${p0.profile.excludedFoods.join(", ")}. Structure: ${p0.mealConfig.meals} meals + ${p0.mealConfig.snacks} snack.`);
L.push("");
L.push(`Machine verification: **${okDays}/${DAYS} days inside every band (post-rounding)** · **${hits.length} allergen hits** across ${run.days.reduce((n, d) => n + d.scan.ingredientCount, 0)} plated ingredients · pool ${run.poolSize} recipes.`);
L.push("");
L.push(`Weigh everything. The grams ARE the prescription — a $15 kitchen scale is the difference between guessing and knowing.`);
L.push("");

for (const d of run.days) {
  const v = d.verdict;
  L.push(`## Day ${d.day} — ${r0(v.read.kcal)} kcal · ${r0(v.read.proteinG)} P · ${r0(v.read.fatG)} F · ${r0(v.read.netCarbG)} netC ${d.ok ? "✓" : `— ${d.diagnosis}`}`);
  L.push("");
  L.push(`\`${d.scanLine}\``);
  L.push("");
  for (const s of d.slots) {
    const title = s.slotType === "meal" ? `Meal ${s.slotIndex + 1}` : `Snack ${s.slotIndex + 1}`;
    for (const dish of s.dishes) {
      L.push(`**${title}: ${dish.recipeName}** — ${r0(dish.totals.kcal)} kcal · ${r0(dish.totals.protein)} g protein`);
      for (const i of dish.ingredients) L.push(`- ${i.grams} g ${i.name}`);
      const recipe = rows.find((r) => r.id === dish.recipeId);
      const steps = Array.isArray(recipe?.steps) ? recipe.steps : [];
      if (steps.length) {
        L.push("");
        steps.forEach((st, i) => L.push(`${i + 1}. ${st}`));
      }
      L.push("");
    }
  }
}

// ── consolidated grocery list over the whole run ────────────────────────────
const totals = new Map(); // name -> grams
for (const d of run.days) for (const s of d.slots) for (const dish of s.dishes) for (const i of dish.ingredients) {
  totals.set(i.name, (totals.get(i.name) || 0) + i.grams);
}
const bySection = new Map();
for (const [name, grams] of totals) {
  const section = classifyStoreSection(name);
  const list = bySection.get(section) || [];
  const purchase = toPurchaseUnits(name, grams);
  list.push({ name, grams: Math.round(grams), purchase });
  bySection.set(section, list);
}
L.push(`## Grocery list — everything above, consolidated (${DAYS} days)`);
L.push("");
L.push("Grams are as-prepared totals; buy amounts are honest approximations.");
L.push("");
for (const [section, items] of [...bySection.entries()].sort()) {
  L.push(`### ${section}`);
  for (const it of items.sort((a, b) => b.grams - a.grams)) {
    const buy = it.purchase?.label ? ` — buy ≈ ${it.purchase.label}` : "";
    L.push(`- ${it.name}: ${it.grams} g${buy}`);
  }
  L.push("");
}

L.push("---");
L.push("Generated by `backend/scripts/prescribeWeek.mjs` from the rebuild QA pool. " +
  "Numbers are FDC-canonical sums over the rounded grams (never 4/4/9); " +
  "every plate re-scanned against the exclusion gate at assembly.");

fs.writeFileSync(OUT, L.join("\n"));
console.log(`ok ${okDays}/${DAYS} · allergen hits ${hits.length} · → ${OUT}`);
