// AUTO-GENERATED by scripts/seed-recipes.mjs on 2026-07-12T20:26:27.579Z.
// DO NOT hand-edit - re-run the seed script instead. Offline FDC per-100g
// macro lookup table for every ingredient fdcId referenced by
// src/data/recipeLibrary.js - the solver reads this instead of calling the
// live FDC API (SOLVER_SPEC_v2.md S9: "Solver reads cache only; API calls
// live in explicit seed/refresh scripts"). Keyed by fdcId (string, since
// JS object keys are always strings).
export const FDC_MACRO_CACHE = {
  "167528": {
    "kcal": 379,
    "protein": 5.48,
    "fat": 18.5,
    "carb": 47.8,
    "fiber": 2.2,
    "description": "Pastry, Pastelitos de Guava (guava pastries)"
  },
  "167529": {
    "kcal": 433,
    "protein": 14.2,
    "fat": 13.4,
    "carb": 64.4,
    "fiber": 3.8,
    "description": "Crackers, snack, Goya Crackers"
  },
  "167532": {
    "kcal": 238,
    "protein": 10.7,
    "fat": 2.15,
    "carb": 43.9,
    "fiber": 9.2,
    "description": "Bread, white wheat"
  },
  "167571": {
    "kcal": 539,
    "protein": 5.87,
    "fat": 32.1,
    "carb": 59.2,
    "fiber": 0.2,
    "description": "Candies, white chocolate"
  },
  "167587": {
    "kcal": 535,
    "protein": 7.65,
    "fat": 29.7,
    "carb": 59.4,
    "fiber": 3.4,
    "description": "Candies, milk chocolate"
  },
  "167626": {
    "kcal": 104,
    "protein": 11,
    "fat": 4.4,
    "carb": 5.1,
    "fiber": 0,
    "description": "Fish, whitefish, broad, liver (Alaska Native)"
  },
  "167628": {
    "kcal": 398,
    "protein": 10.4,
    "fat": 5.44,
    "carb": 76.9,
    "fiber": 8.7,
    "description": "Cornmeal, blue (Navajo)"
  },
  "167631": {
    "kcal": 386,
    "protein": 9.88,
    "fat": 5.22,
    "carb": 74.9,
    "fiber": 0,
    "description": "Corn, dried (Navajo)"
  },
  "167656": {
    "kcal": 224,
    "protein": 7.91,
    "fat": 8.31,
    "carb": 29.4,
    "fiber": 1.5,
    "description": "Corned beef and potatoes in tortilla (Apache)"
  },
  "167673": {
    "kcal": 182,
    "protein": 28.9,
    "fat": 7.34,
    "carb": 0.14,
    "fiber": 0,
    "description": "DENNY'S, top sirloin steak"
  },
  "167682": {
    "kcal": 11,
    "protein": 0,
    "fat": 0,
    "carb": 2.1,
    "fiber": 2.1,
    "description": "Pectin, liquid"
  },
  "167702": {
    "kcal": 884,
    "protein": 0.11,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, flaxseed, cold pressed"
  },
  "167717": {
    "kcal": 185,
    "protein": 23.9,
    "fat": 0.9,
    "carb": 20.4,
    "fiber": 6.5,
    "description": "Yeast extract spread"
  },
  "167722": {
    "kcal": 94,
    "protein": 3.5,
    "fat": 1.8,
    "carb": 16,
    "fiber": 0.2,
    "description": "Tofu yogurt"
  },
  "167723": {
    "kcal": 134,
    "protein": 0.5,
    "fat": 0,
    "carb": 5,
    "fiber": 0,
    "description": "Alcoholic beverage, rice (sake)"
  },
  "167737": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, corn, peanut, and olive"
  },
  "167747": {
    "kcal": 22,
    "protein": 0.35,
    "fat": 0.24,
    "carb": 6.9,
    "fiber": 0.3,
    "description": "Lemon juice, raw"
  },
  "167758": {
    "kcal": 21,
    "protein": 0.9,
    "fat": 0.2,
    "carb": 4.54,
    "fiber": 1.8,
    "description": "Rhubarb, raw"
  },
  "167762": {
    "kcal": 32,
    "protein": 0.67,
    "fat": 0.3,
    "carb": 7.68,
    "fiber": 2,
    "description": "Strawberries, raw"
  },
  "167774": {
    "kcal": 39,
    "protein": 0.5,
    "fat": 0.1,
    "carb": 9.2,
    "fiber": 0,
    "description": "Grapefruit juice, pink, raw"
  },
  "167780": {
    "kcal": 257,
    "protein": 2.1,
    "fat": 0.2,
    "carb": 65.1,
    "fiber": 3.3,
    "description": "Prune puree"
  },
  "167802": {
    "kcal": 17,
    "protein": 0.47,
    "fat": 0.07,
    "carb": 5.66,
    "fiber": 0.7,
    "description": "Lemon juice from concentrate, bottled, REAL LEMON"
  },
  "167806": {
    "kcal": 250,
    "protein": 3.69,
    "fat": 0.47,
    "carb": 79.6,
    "fiber": 44.5,
    "description": "Baobab powder"
  },
  "167849": {
    "kcal": 186,
    "protein": 17.4,
    "fat": 12.4,
    "carb": 0,
    "fiber": 0,
    "description": "Pork, fresh, shoulder, (Boston butt), blade (steaks), separable lean and fat, raw"
  },
  "167940": {
    "kcal": 452,
    "protein": 4.45,
    "fat": 26.6,
    "carb": 48.6,
    "fiber": 1.2,
    "description": "Cinnamon buns, frosted (includes honey buns)"
  },
  "167943": {
    "kcal": 266,
    "protein": 12.5,
    "fat": 3.13,
    "carb": 47.1,
    "fiber": 6.3,
    "description": "Bread, potato"
  },
  "167944": {
    "kcal": 408,
    "protein": 10.4,
    "fat": 20.8,
    "carb": 44.8,
    "fiber": 2.1,
    "description": "Bread, cheese"
  },
  "167946": {
    "kcal": 387,
    "protein": 16.8,
    "fat": 14.3,
    "carb": 56.5,
    "fiber": 2.3,
    "description": "SCHIFF,TIGER'S MILK BAR"
  },
  "167974": {
    "kcal": 382,
    "protein": 4.6,
    "fat": 8.1,
    "carb": 77,
    "fiber": 0,
    "description": "Candies, caramels"
  },
  "167977": {
    "kcal": 507,
    "protein": 3.9,
    "fat": 34.2,
    "carb": 60.4,
    "fiber": 5.5,
    "description": "Candies, sweet chocolate"
  },
  "167994": {
    "kcal": 467,
    "protein": 8.1,
    "fat": 23,
    "carb": 62.7,
    "fiber": 2,
    "description": "Candies, MARS SNACKFOOD US, MARS Almond Bar"
  },
  "168022": {
    "kcal": 61,
    "protein": 4.2,
    "fat": 0.5,
    "carb": 9.9,
    "fiber": 0,
    "description": "Rhubarb, wild, leaves (Alaska Native)"
  },
  "168038": {
    "kcal": 398,
    "protein": 11,
    "fat": 5.04,
    "carb": 77.1,
    "fiber": 10.4,
    "description": "Cornmeal, white (Navajo)"
  },
  "168039": {
    "kcal": 384,
    "protein": 9.85,
    "fat": 5.88,
    "carb": 72.9,
    "fiber": 9.4,
    "description": "Cornmeal, yellow (Navajo)"
  },
  "168056": {
    "kcal": 97,
    "protein": 20.1,
    "fat": 1.8,
    "carb": 0,
    "fiber": 0,
    "description": "Elk, free range, ground, raw (Shoshone Bannock)"
  },
  "168058": {
    "kcal": 156,
    "protein": 2.89,
    "fat": 0.98,
    "carb": 33.9,
    "fiber": 17,
    "description": "Chokecherries, raw, pitted (Shoshone Bannock)"
  },
  "168070": {
    "kcal": 219,
    "protein": 5.48,
    "fat": 5.38,
    "carb": 37.1,
    "fiber": 2.6,
    "description": "Restaurant, Latino, arepa (unleavened cornmeal bread)"
  },
  "168087": {
    "kcal": 293,
    "protein": 14.3,
    "fat": 14.2,
    "carb": 26.9,
    "fiber": 0.7,
    "description": "Restaurant, Chinese, sesame chicken"
  },
  "168092": {
    "kcal": 134,
    "protein": 19.6,
    "fat": 5.8,
    "carb": 0.93,
    "fiber": 0,
    "description": "Ham, turkey, sliced, extra lean, prepackaged or deli"
  },
  "168093": {
    "kcal": 564,
    "protein": 1.2,
    "fat": 61.4,
    "carb": 3.5,
    "fiber": 0,
    "description": "Salad dressing, peppercorn dressing, commercial, regular"
  },
  "168112": {
    "kcal": 263,
    "protein": 0.9,
    "fat": 19,
    "carb": 23.9,
    "fiber": 0,
    "description": "Salad dressing, mayonnaise and mayonnaise-type, low calorie"
  },
  "168148": {
    "kcal": 73,
    "protein": 16.4,
    "fat": 0.3,
    "carb": 0,
    "fiber": 0,
    "description": "Frog legs, raw"
  },
  "168149": {
    "kcal": 305,
    "protein": 18.5,
    "fat": 25.1,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, mackerel, salted"
  },
  "168155": {
    "kcal": 30,
    "protein": 0.7,
    "fat": 0.2,
    "carb": 10.5,
    "fiber": 2.8,
    "description": "Limes, raw"
  },
  "168156": {
    "kcal": 25,
    "protein": 0.42,
    "fat": 0.07,
    "carb": 8.42,
    "fiber": 0.4,
    "description": "Lime juice, raw"
  },
  "168164": {
    "kcal": 301,
    "protein": 3.28,
    "fat": 0.2,
    "carb": 80,
    "fiber": 3.3,
    "description": "Raisins, golden, seedless"
  },
  "168166": {
    "kcal": 296,
    "protein": 2.52,
    "fat": 0.54,
    "carb": 78.5,
    "fiber": 6.8,
    "description": "Raisins, seeded"
  },
  "168171": {
    "kcal": 25,
    "protein": 0.6,
    "fat": 0.3,
    "carb": 5.7,
    "fiber": 0,
    "description": "Rose-apples, raw"
  },
  "168191": {
    "kcal": 277,
    "protein": 1.81,
    "fat": 0.15,
    "carb": 75,
    "fiber": 6.7,
    "description": "Dates, medjool"
  },
  "168216": {
    "kcal": 121,
    "protein": 1.09,
    "fat": 0.08,
    "carb": 29.2,
    "fiber": 2.6,
    "description": "Plantains, green, boiled"
  },
  "168389": {
    "kcal": 20,
    "protein": 2.2,
    "fat": 0.12,
    "carb": 3.88,
    "fiber": 2.1,
    "description": "Asparagus, raw"
  },
  "168396": {
    "kcal": 113,
    "protein": 6.84,
    "fat": 0.86,
    "carb": 20.2,
    "fiber": 4.9,
    "description": "Lima beans, immature seeds, raw"
  },
  "168416": {
    "kcal": 64,
    "protein": 9.4,
    "fat": 1.4,
    "carb": 8.28,
    "fiber": 2,
    "description": "Drumstick leaves, raw"
  },
  "168421": {
    "kcal": 35,
    "protein": 2.92,
    "fat": 1.49,
    "carb": 4.42,
    "fiber": 4.1,
    "description": "Kale, raw"
  },
  "168435": {
    "kcal": 39,
    "protein": 3.45,
    "fat": 0.35,
    "carb": 7.68,
    "fiber": 3.6,
    "description": "Mushrooms, shiitake, stir-fried"
  },
  "168440": {
    "kcal": 14,
    "protein": 1.5,
    "fat": 0.2,
    "carb": 2.5,
    "fiber": 1.5,
    "description": "New Zealand spinach, raw"
  },
  "168448": {
    "kcal": 26,
    "protein": 1,
    "fat": 0.1,
    "carb": 6.5,
    "fiber": 0.5,
    "description": "Pumpkin, raw"
  },
  "168454": {
    "kcal": 37,
    "protein": 1.08,
    "fat": 0.16,
    "carb": 8.62,
    "fiber": 2.3,
    "description": "Rutabagas, raw"
  },
  "168478": {
    "kcal": 77,
    "protein": 2.64,
    "fat": 0.54,
    "carb": 17.6,
    "fiber": 3,
    "description": "Succotash, (corn and limas), canned, with cream style corn"
  },
  "168565": {
    "kcal": 21,
    "protein": 2.71,
    "fat": 0.4,
    "carb": 3.11,
    "fiber": 1.1,
    "description": "Squash, zucchini, baby, raw"
  },
  "168567": {
    "kcal": 258,
    "protein": 14.1,
    "fat": 2.97,
    "carb": 55.8,
    "fiber": 12.3,
    "description": "Tomatoes, sun-dried"
  },
  "168569": {
    "kcal": 28,
    "protein": 2.52,
    "fat": 0.62,
    "carb": 4.62,
    "fiber": 2.4,
    "description": "Hearts of palm, canned"
  },
  "168572": {
    "kcal": 12,
    "protein": 1.1,
    "fat": 0.17,
    "carb": 2.23,
    "fiber": 0,
    "description": "Cabbage, napa, cooked"
  },
  "168576": {
    "kcal": 29,
    "protein": 0.91,
    "fat": 0.37,
    "carb": 6.5,
    "fiber": 2.8,
    "description": "Peppers, jalapeno, raw"
  },
  "168577": {
    "kcal": 21,
    "protein": 0.72,
    "fat": 0.27,
    "carb": 4.6,
    "fiber": 1.7,
    "description": "Peppers, chili, green, canned"
  },
  "168581": {
    "kcal": 284,
    "protein": 9.25,
    "fat": 0.73,
    "carb": 73,
    "fiber": 70.1,
    "description": "Fungi, Cloud ears, dried"
  },
  "168585": {
    "kcal": 684,
    "protein": 5.3,
    "fat": 69.1,
    "carb": 21.5,
    "fiber": 0,
    "description": "Nuts, coconut meat, dried (desiccated), creamed"
  },
  "168604": {
    "kcal": 592,
    "protein": 17.4,
    "fat": 53,
    "carb": 21.5,
    "fiber": 4.7,
    "description": "Seeds, sesame butter, tahini, type of kernels unspecified"
  },
  "168606": {
    "kcal": 680,
    "protein": 10.6,
    "fat": 70.3,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, retail cuts, separable fat, cooked"
  },
  "168749": {
    "kcal": 29,
    "protein": 0.24,
    "fat": 0,
    "carb": 1.64,
    "fiber": 0,
    "description": "Alcoholic beverage, beer, light"
  },
  "168754": {
    "kcal": 526,
    "protein": 9,
    "fat": 34.4,
    "carb": 53.4,
    "fiber": 6.2,
    "description": "Candies, milk chocolate, with almonds"
  },
  "168757": {
    "kcal": 541,
    "protein": 3.13,
    "fat": 30.4,
    "carb": 63.7,
    "fiber": 1.3,
    "description": "Candies, HERSHEY'S SKOR Toffee Bar"
  },
  "168761": {
    "kcal": 468,
    "protein": 2.5,
    "fat": 19.3,
    "carb": 71,
    "fiber": 1,
    "description": "Candies, NESTLE, 100 GRAND Bar"
  },
  "168766": {
    "kcal": 432,
    "protein": 1.67,
    "fat": 11.9,
    "carb": 79.5,
    "fiber": 2.4,
    "description": "Candies, NESTLE, AFTER EIGHT Mints"
  },
  "168772": {
    "kcal": 410,
    "protein": 6.9,
    "fat": 6.4,
    "carb": 82.8,
    "fiber": 0,
    "description": "Egg custards, dry mix"
  },
  "168775": {
    "kcal": 381,
    "protein": 7.8,
    "fat": 0,
    "carb": 90.5,
    "fiber": 0,
    "description": "Gelatin desserts, dry mix"
  },
  "168819": {
    "kcal": 246,
    "protein": 0.3,
    "fat": 0,
    "carb": 66.3,
    "fiber": 0.7,
    "description": "Marmalade, orange"
  },
  "168820": {
    "kcal": 290,
    "protein": 0,
    "fat": 0.1,
    "carb": 74.7,
    "fiber": 0,
    "description": "Molasses"
  },
  "168833": {
    "kcal": 380,
    "protein": 0.12,
    "fat": 0,
    "carb": 98.1,
    "fiber": 0,
    "description": "Sugars, brown"
  },
  "168895": {
    "kcal": 354,
    "protein": 9.89,
    "fat": 0.97,
    "carb": 74.2,
    "fiber": 2.7,
    "description": "Wheat flour, white, all-purpose, self-rising, enriched"
  },
  "168913": {
    "kcal": 361,
    "protein": 12,
    "fat": 1.66,
    "carb": 72.5,
    "fiber": 2.4,
    "description": "Wheat flours, bread, unenriched"
  },
  "168914": {
    "kcal": 108,
    "protein": 1.79,
    "fat": 0.2,
    "carb": 24,
    "fiber": 1,
    "description": "Rice noodles, cooked"
  },
  "168917": {
    "kcal": 120,
    "protein": 4.4,
    "fat": 1.92,
    "carb": 21.3,
    "fiber": 2.8,
    "description": "Quinoa, cooked"
  },
  "168944": {
    "kcal": 332,
    "protein": 9.61,
    "fat": 1.95,
    "carb": 74.5,
    "fiber": 13.1,
    "description": "Wheat flour, whole-grain, soft wheat"
  },
  "168951": {
    "kcal": 359,
    "protein": 10.4,
    "fat": 1.37,
    "carb": 76.3,
    "fiber": 1.2,
    "description": "Rice and vermicelli mix, rice pilaf flavor, unprepared"
  },
  "168956": {
    "kcal": 343,
    "protein": 7.02,
    "fat": 1.75,
    "carb": 74.7,
    "fiber": 1.8,
    "description": "Yellow rice with seasoning, dry packet mix, unprepared"
  },
  "169011": {
    "kcal": 316,
    "protein": 14.9,
    "fat": 18.4,
    "carb": 22.9,
    "fiber": 2.1,
    "description": "APPLEBEE'S, mozzarella sticks"
  },
  "169024": {
    "kcal": 234,
    "protein": 13.8,
    "fat": 12.2,
    "carb": 17.4,
    "fiber": 1,
    "description": "DENNY'S, fish fillet, battered or breaded, fried"
  },
  "169030": {
    "kcal": 191,
    "protein": 10.5,
    "fat": 11.1,
    "carb": 12.4,
    "fiber": 1.3,
    "description": "CARRABBA'S ITALIAN GRILL, lasagne"
  },
  "169032": {
    "kcal": 144,
    "protein": 7.3,
    "fat": 5,
    "carb": 17.5,
    "fiber": 8.2,
    "description": "ON THE BORDER, refried beans"
  },
  "169068": {
    "kcal": 290,
    "protein": 23,
    "fat": 18,
    "carb": 9,
    "fiber": 6.1,
    "description": "Vegetarian fillets"
  },
  "169070": {
    "kcal": 50,
    "protein": 0.5,
    "fat": 0,
    "carb": 6.3,
    "fiber": 0,
    "description": "Alcoholic beverage, wine, cooking"
  },
  "169078": {
    "kcal": 95,
    "protein": 10.9,
    "fat": 4.2,
    "carb": 3,
    "fiber": 0.1,
    "description": "Cheese, cottage, with vegetables"
  },
  "169081": {
    "kcal": 295,
    "protein": 7.1,
    "fat": 28.6,
    "carb": 3.5,
    "fiber": 0,
    "description": "Cheese spread, cream cheese base"
  },
  "169083": {
    "kcal": 151,
    "protein": 12.5,
    "fat": 8.1,
    "carb": 6.9,
    "fiber": 0,
    "description": "Soybean, curd cheese"
  },
  "169087": {
    "kcal": 277,
    "protein": 3.8,
    "fat": 1.2,
    "carb": 70.7,
    "fiber": 4.6,
    "description": "Litchis, dried"
  },
  "169088": {
    "kcal": 55,
    "protein": 1.52,
    "fat": 0.31,
    "carb": 13,
    "fiber": 5.3,
    "description": "Loganberries, frozen"
  },
  "169089": {
    "kcal": 60,
    "protein": 1.31,
    "fat": 0.1,
    "carb": 15.1,
    "fiber": 1.1,
    "description": "Longans, raw"
  },
  "169100": {
    "kcal": 49,
    "protein": 0.68,
    "fat": 0.12,
    "carb": 11.5,
    "fiber": 0.3,
    "description": "Orange juice, chilled, includes from concentrate"
  },
  "169109": {
    "kcal": 51,
    "protein": 0.39,
    "fat": 0.05,
    "carb": 13.6,
    "fiber": 0.2,
    "description": "Passion-fruit juice, purple, raw"
  },
  "169118": {
    "kcal": 57,
    "protein": 0.36,
    "fat": 0.14,
    "carb": 15.2,
    "fiber": 3.1,
    "description": "Pears, raw"
  },
  "169134": {
    "kcal": 83,
    "protein": 1.67,
    "fat": 1.17,
    "carb": 18.7,
    "fiber": 4,
    "description": "Pomegranates, raw"
  },
  "169157": {
    "kcal": 171,
    "protein": 19.1,
    "fat": 10.5,
    "carb": 0,
    "fiber": 0,
    "description": "Pork, pickled pork hocks"
  },
  "169187": {
    "kcal": 127,
    "protein": 22.5,
    "fat": 3.4,
    "carb": 0,
    "fiber": 0,
    "description": "Pork, Shoulder breast, boneless, separable lean and fat, raw"
  },
  "169210": {
    "kcal": 27,
    "protein": 2.6,
    "fat": 0.3,
    "carb": 5.2,
    "fiber": 2.2,
    "description": "Bamboo shoots, raw"
  },
  "169213": {
    "kcal": 29,
    "protein": 4.2,
    "fat": 0.5,
    "carb": 4.1,
    "fiber": 0,
    "description": "Beans, kidney, mature seeds, sprouted, raw"
  },
  "169225": {
    "kcal": 10,
    "protein": 0.59,
    "fat": 0.16,
    "carb": 2.16,
    "fiber": 0.7,
    "description": "Cucumber, peeled, raw"
  },
  "169228": {
    "kcal": 25,
    "protein": 0.98,
    "fat": 0.18,
    "carb": 5.88,
    "fiber": 3,
    "description": "Eggplant, raw"
  },
  "169231": {
    "kcal": 80,
    "protein": 1.82,
    "fat": 0.75,
    "carb": 17.8,
    "fiber": 2,
    "description": "Ginger root, raw"
  },
  "169236": {
    "kcal": 73,
    "protein": 2,
    "fat": 0.01,
    "carb": 17.4,
    "fiber": 1.6,
    "description": "Jerusalem-artichokes, raw"
  },
  "169246": {
    "kcal": 61,
    "protein": 1.5,
    "fat": 0.3,
    "carb": 14.2,
    "fiber": 1.8,
    "description": "Leeks, (bulb and lower leaf-portion), raw"
  },
  "169276": {
    "kcal": 16,
    "protein": 0.68,
    "fat": 0.1,
    "carb": 3.4,
    "fiber": 1.6,
    "description": "Radishes, raw"
  },
  "169279": {
    "kcal": 19,
    "protein": 0.91,
    "fat": 0.14,
    "carb": 4.28,
    "fiber": 2.9,
    "description": "Sauerkraut, canned, solids and liquids"
  },
  "169289": {
    "kcal": 18,
    "protein": 1.2,
    "fat": 0.2,
    "carb": 3.84,
    "fiber": 1.2,
    "description": "Squash, summer, scallop, raw"
  },
  "169295": {
    "kcal": 45,
    "protein": 1,
    "fat": 0.1,
    "carb": 11.7,
    "fiber": 2,
    "description": "Squash, winter, butternut, raw"
  },
  "169301": {
    "kcal": 19,
    "protein": 2.6,
    "fat": 0.2,
    "carb": 3.13,
    "fiber": 2.1,
    "description": "Water convolvulus,raw"
  },
  "169303": {
    "kcal": 42,
    "protein": 2.49,
    "fat": 0.51,
    "carb": 8.82,
    "fiber": 5.3,
    "description": "Sweet potato leaves, raw"
  },
  "169308": {
    "kcal": 112,
    "protein": 1.5,
    "fat": 0.2,
    "carb": 26.5,
    "fiber": 4.1,
    "description": "Taro, raw"
  },
  "169331": {
    "kcal": 28,
    "protein": 2.98,
    "fat": 0.35,
    "carb": 5.24,
    "fiber": 0,
    "description": "Broccoli, stalks, raw"
  },
  "169342": {
    "kcal": 18,
    "protein": 0.83,
    "fat": 0.16,
    "carb": 4,
    "fiber": 1.6,
    "description": "Celery, cooked, boiled, drained, with salt"
  },
  "169345": {
    "kcal": 61,
    "protein": 1.95,
    "fat": 0.77,
    "carb": 13.9,
    "fiber": 1.7,
    "description": "Corn, sweet, yellow, canned, no salt added, solids and liquids (Includes foods for USDA's Food Distribution Program)"
  },
  "169365": {
    "kcal": 98,
    "protein": 3.28,
    "fat": 0.78,
    "carb": 23.5,
    "fiber": 2.8,
    "description": "Corn, sweet, white, frozen, kernels on cob, unprepared"
  },
  "169373": {
    "kcal": 314,
    "protein": 17.9,
    "fat": 3,
    "carb": 68.7,
    "fiber": 21.3,
    "description": "Peppers, sweet, red, freeze-dried"
  },
  "169387": {
    "kcal": 25,
    "protein": 2.58,
    "fat": 0.66,
    "carb": 3.65,
    "fiber": 1.6,
    "description": "Arugula, raw"
  },
  "169392": {
    "kcal": 22,
    "protein": 1.14,
    "fat": 0.72,
    "carb": 3.81,
    "fiber": 2.5,
    "description": "Broccoli, chinese, cooked"
  },
  "169393": {
    "kcal": 69,
    "protein": 4.27,
    "fat": 1.97,
    "carb": 11.7,
    "fiber": 9.9,
    "description": "Grape leaves, canned"
  },
  "169394": {
    "kcal": 27,
    "protein": 1.66,
    "fat": 0.45,
    "carb": 5.35,
    "fiber": 3.4,
    "description": "Pepper, banana, raw"
  },
  "169395": {
    "kcal": 32,
    "protein": 1.74,
    "fat": 0.44,
    "carb": 6.7,
    "fiber": 3.7,
    "description": "Peppers, serrano, raw"
  },
  "169396": {
    "kcal": 281,
    "protein": 11.9,
    "fat": 8.2,
    "carb": 51.4,
    "fiber": 21.6,
    "description": "Peppers, ancho, dried"
  },
  "169401": {
    "kcal": 98,
    "protein": 1.46,
    "fat": 0.4,
    "carb": 23.6,
    "fiber": 1.5,
    "description": "Yautia (tannier), raw"
  },
  "169422": {
    "kcal": 581,
    "protein": 16.8,
    "fat": 47.8,
    "carb": 30.2,
    "fiber": 3.3,
    "description": "Nuts, cashew nuts, oil roasted, with salt added"
  },
  "169429": {
    "kcal": 117,
    "protein": 23.1,
    "fat": 2.69,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, grass-fed, strip steaks, lean only, raw"
  },
  "169430": {
    "kcal": 291,
    "protein": 17.3,
    "fat": 24,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, carcass, separable lean and fat, choice, raw"
  },
  "169586": {
    "kcal": 486,
    "protein": 7.57,
    "fat": 19,
    "carb": 71.2,
    "fiber": 2.5,
    "description": "Candies, peanut brittle, prepared-from-recipe"
  },
  "169592": {
    "kcal": 556,
    "protein": 5.54,
    "fat": 32.4,
    "carb": 60.5,
    "fiber": 6.5,
    "description": "Candies, SPECIAL DARK Chocolate Bar"
  },
  "169593": {
    "kcal": 228,
    "protein": 19.6,
    "fat": 13.7,
    "carb": 57.9,
    "fiber": 37,
    "description": "Cocoa, dry powder, unsweetened"
  },
  "169640": {
    "kcal": 304,
    "protein": 0.3,
    "fat": 0,
    "carb": 82.4,
    "fiber": 0.2,
    "description": "Honey"
  },
  "169641": {
    "kcal": 278,
    "protein": 0.37,
    "fat": 0.07,
    "carb": 68.9,
    "fiber": 1.1,
    "description": "Jams and preserves"
  },
  "169656": {
    "kcal": 389,
    "protein": 0,
    "fat": 0,
    "carb": 99.8,
    "fiber": 0,
    "description": "Sugars, powdered"
  },
  "169660": {
    "kcal": 318,
    "protein": 6.2,
    "fat": 0,
    "carb": 71.3,
    "fiber": 0,
    "description": "Syrups, malt"
  },
  "169661": {
    "kcal": 260,
    "protein": 0.04,
    "fat": 0.06,
    "carb": 67,
    "fiber": 0,
    "description": "Syrups, maple"
  },
  "169685": {
    "kcal": 381,
    "protein": 2,
    "fat": 1.4,
    "carb": 90.1,
    "fiber": 2.5,
    "description": "Popcorn, sugar syrup/caramel, fat-free"
  },
  "169687": {
    "kcal": 417,
    "protein": 3.4,
    "fat": 9,
    "carb": 80.5,
    "fiber": 0,
    "description": "Snacks, KELLOGG, KELLOGG'S RICE KRISPIES TREATS Squares"
  },
  "169694": {
    "kcal": 363,
    "protein": 8.46,
    "fat": 3.69,
    "carb": 76.6,
    "fiber": 6.4,
    "description": "Corn flour, masa, enriched, white"
  },
  "169698": {
    "kcal": 381,
    "protein": 0.26,
    "fat": 0.05,
    "carb": 91.3,
    "fiber": 0.9,
    "description": "Cornstarch"
  },
  "169700": {
    "kcal": 112,
    "protein": 3.79,
    "fat": 0.16,
    "carb": 23.2,
    "fiber": 1.4,
    "description": "Couscous, cooked"
  },
  "169715": {
    "kcal": 360,
    "protein": 12.7,
    "fat": 1.05,
    "carb": 72.8,
    "fiber": 3.9,
    "description": "Semolina, enriched"
  },
  "169717": {
    "kcal": 358,
    "protein": 0.19,
    "fat": 0.02,
    "carb": 88.7,
    "fiber": 0.9,
    "description": "Tapioca, pearl, dry"
  },
  "169725": {
    "kcal": 198,
    "protein": 7.49,
    "fat": 1.27,
    "carb": 42.5,
    "fiber": 1.1,
    "description": "Wheat, sprouted"
  },
  "169731": {
    "kcal": 384,
    "protein": 14.2,
    "fat": 4.44,
    "carb": 71.3,
    "fiber": 3.3,
    "description": "Noodles, egg, dry, enriched"
  },
  "169735": {
    "kcal": 521,
    "protein": 10.3,
    "fat": 31.7,
    "carb": 51.9,
    "fiber": 1.9,
    "description": "Noodles, flat, crunchy, Chinese restaurant"
  },
  "169736": {
    "kcal": 371,
    "protein": 13,
    "fat": 1.51,
    "carb": 74.7,
    "fiber": 3.2,
    "description": "Pasta, dry, enriched"
  },
  "169738": {
    "kcal": 352,
    "protein": 13.9,
    "fat": 2.93,
    "carb": 73.4,
    "fiber": 9.2,
    "description": "Pasta, whole-wheat, dry (Includes foods for USDA's Food Distribution Program)"
  },
  "169801": {
    "kcal": 326,
    "protein": 10.8,
    "fat": 31.4,
    "carb": 0,
    "fiber": 0,
    "description": "Caribou, eye, raw (Alaska Native)"
  },
  "169845": {
    "kcal": 170,
    "protein": 7.84,
    "fat": 8.52,
    "carb": 15.5,
    "fiber": 1.5,
    "description": "DENNY'S, spaghetti and meatballs"
  },
  "169878": {
    "kcal": 51,
    "protein": 0.8,
    "fat": 0,
    "carb": 12,
    "fiber": 0.7,
    "description": "Syrups, sugar free"
  },
  "169884": {
    "kcal": 331,
    "protein": 0.1,
    "fat": 0.1,
    "carb": 82.3,
    "fiber": 3.9,
    "description": "Vermicelli, made from soy"
  },
  "169885": {
    "kcal": 47,
    "protein": 1.8,
    "fat": 3.2,
    "carb": 2.8,
    "fiber": 0.1,
    "description": "Beans, liquid from stewed kidney beans"
  },
  "169892": {
    "kcal": 49,
    "protein": 0.9,
    "fat": 0.7,
    "carb": 9.77,
    "fiber": 2.5,
    "description": "Eggplant, pickled"
  },
  "169910": {
    "kcal": 60,
    "protein": 0.82,
    "fat": 0.38,
    "carb": 15,
    "fiber": 1.6,
    "description": "Mangos, raw"
  },
  "169912": {
    "kcal": 33,
    "protein": 0.84,
    "fat": 0.25,
    "carb": 7.94,
    "fiber": 0.7,
    "description": "Melon balls, frozen"
  },
  "169946": {
    "kcal": 86,
    "protein": 0.4,
    "fat": 0.1,
    "carb": 22.2,
    "fiber": 1.1,
    "description": "Pineapple, frozen, chunks, sweetened"
  },
  "169949": {
    "kcal": 46,
    "protein": 0.7,
    "fat": 0.28,
    "carb": 11.4,
    "fiber": 1.4,
    "description": "Plums, raw"
  },
  "169957": {
    "kcal": 30,
    "protein": 3.04,
    "fat": 0.18,
    "carb": 5.94,
    "fiber": 1.8,
    "description": "Mung beans, mature seeds, sprouted, raw"
  },
  "169965": {
    "kcal": 33,
    "protein": 2.31,
    "fat": 0.5,
    "carb": 6.41,
    "fiber": 3.4,
    "description": "Beans, snap, green, microwaved"
  },
  "169977": {
    "kcal": 31,
    "protein": 1.43,
    "fat": 0.16,
    "carb": 7.37,
    "fiber": 2.1,
    "description": "Cabbage, red, raw"
  },
  "169985": {
    "kcal": 160,
    "protein": 1.36,
    "fat": 0.28,
    "carb": 38.1,
    "fiber": 1.8,
    "description": "Cassava, raw"
  },
  "169994": {
    "kcal": 30,
    "protein": 3.27,
    "fat": 0.73,
    "carb": 4.35,
    "fiber": 2.5,
    "description": "Chives, raw"
  },
  "169997": {
    "kcal": 23,
    "protein": 2.13,
    "fat": 0.52,
    "carb": 3.67,
    "fiber": 2.8,
    "description": "Coriander (cilantro) leaves, raw"
  },
  "169998": {
    "kcal": 86,
    "protein": 3.27,
    "fat": 1.35,
    "carb": 18.7,
    "fiber": 2,
    "description": "Corn, sweet, yellow, raw"
  },
  "170000": {
    "kcal": 40,
    "protein": 1.1,
    "fat": 0.1,
    "carb": 9.34,
    "fiber": 1.7,
    "description": "Onions, raw"
  },
  "170002": {
    "kcal": 349,
    "protein": 8.95,
    "fat": 0.46,
    "carb": 83.3,
    "fiber": 9.2,
    "description": "Onions, dehydrated flakes"
  },
  "170005": {
    "kcal": 32,
    "protein": 1.83,
    "fat": 0.19,
    "carb": 7.34,
    "fiber": 2.6,
    "description": "Onions, spring or scallions (includes tops and bulb), raw"
  },
  "170030": {
    "kcal": 95,
    "protein": 2.63,
    "fat": 0.13,
    "carb": 21.4,
    "fiber": 2.3,
    "description": "Potatoes, Russet, flesh and skin, baked"
  },
  "170071": {
    "kcal": 118,
    "protein": 1.53,
    "fat": 0.17,
    "carb": 27.9,
    "fiber": 4.1,
    "description": "Yam, raw"
  },
  "170100": {
    "kcal": 42,
    "protein": 1.36,
    "fat": 0.19,
    "carb": 9.56,
    "fiber": 1.4,
    "description": "Onions, cooked, boiled, drained, with salt"
  },
  "170108": {
    "kcal": 26,
    "protein": 0.99,
    "fat": 0.3,
    "carb": 6.03,
    "fiber": 2.1,
    "description": "Peppers, sweet, red, raw"
  },
  "170132": {
    "kcal": 20,
    "protein": 2.08,
    "fat": 0.24,
    "carb": 3.7,
    "fiber": 1.9,
    "description": "Water convolvulus, cooked, boiled, drained, with salt"
  },
  "170145": {
    "kcal": 168,
    "protein": 5.3,
    "fat": 2.3,
    "carb": 32,
    "fiber": 4.8,
    "description": "Seeds, breadfruit seeds, boiled"
  },
  "170150": {
    "kcal": 573,
    "protein": 17.7,
    "fat": 49.7,
    "carb": 23.4,
    "fiber": 11.8,
    "description": "Seeds, sesame seeds, whole, dried"
  },
  "170160": {
    "kcal": 458,
    "protein": 9,
    "fat": 27.7,
    "carb": 47.8,
    "fiber": 4.8,
    "description": "Nuts, almond paste"
  },
  "170171": {
    "kcal": 357,
    "protein": 1.17,
    "fat": 16.3,
    "carb": 53.2,
    "fiber": 0.2,
    "description": "Nuts, coconut cream, canned, sweetened"
  },
  "170182": {
    "kcal": 691,
    "protein": 9.17,
    "fat": 72,
    "carb": 13.9,
    "fiber": 9.6,
    "description": "Nuts, pecans"
  },
  "170184": {
    "kcal": 560,
    "protein": 20.2,
    "fat": 45.3,
    "carb": 27.2,
    "fiber": 10.6,
    "description": "Nuts, pistachio nuts, raw"
  },
  "170193": {
    "kcal": 854,
    "protein": 1.5,
    "fat": 94,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, variety meats and by-products, suet, raw"
  },
  "170200": {
    "kcal": 251,
    "protein": 18.2,
    "fat": 19,
    "carb": 0.47,
    "fiber": 0,
    "description": "Beef, cured, corned beef, brisket, cooked"
  },
  "170249": {
    "kcal": 381,
    "protein": 9.1,
    "fat": 3.5,
    "carb": 79.2,
    "fiber": 2.8,
    "description": "Snacks, pretzels, hard, plain, made with enriched flour, unsalted"
  },
  "170264": {
    "kcal": 143,
    "protein": 3.68,
    "fat": 6.2,
    "carb": 21.9,
    "fiber": 0.5,
    "description": "Ice creams, BREYERS, No Sugar Added, Vanilla"
  },
  "170274": {
    "kcal": 550,
    "protein": 5.09,
    "fat": 32.2,
    "carb": 60,
    "fiber": 7.2,
    "description": "Candies, chocolate, dark, NFS (45-59% cacao solids 90%; 60-69% cacao solids 5%; 70-85% cacao solids 5%)"
  },
  "170281": {
    "kcal": 331,
    "protein": 0,
    "fat": 0,
    "carb": 92,
    "fiber": 2.5,
    "description": "Candies, Tamarind"
  },
  "170286": {
    "kcal": 343,
    "protein": 13.2,
    "fat": 3.4,
    "carb": 71.5,
    "fiber": 10,
    "description": "Buckwheat"
  },
  "170287": {
    "kcal": 83,
    "protein": 3.08,
    "fat": 0.24,
    "carb": 18.6,
    "fiber": 4.5,
    "description": "Bulgur, cooked"
  },
  "170288": {
    "kcal": 365,
    "protein": 9.42,
    "fat": 4.74,
    "carb": 74.3,
    "fiber": 7.3,
    "description": "Corn grain, yellow"
  },
  "170329": {
    "kcal": 286,
    "protein": 14.6,
    "fat": 14.8,
    "carb": 23.7,
    "fiber": 1,
    "description": "BURGER KING, Cheeseburger"
  },
  "170339": {
    "kcal": 358,
    "protein": 7.5,
    "fat": 17,
    "carb": 43.6,
    "fiber": 2,
    "description": "KFC, biscuit"
  },
  "170388": {
    "kcal": 27,
    "protein": 2,
    "fat": 0.1,
    "carb": 6.1,
    "fiber": 3.1,
    "description": "Cabbage, savoy, raw"
  },
  "170390": {
    "kcal": 13,
    "protein": 1.5,
    "fat": 0.2,
    "carb": 2.18,
    "fiber": 1,
    "description": "Cabbage, chinese (pak-choi), raw"
  },
  "170392": {
    "kcal": 15,
    "protein": 1.1,
    "fat": 0.5,
    "carb": 2.4,
    "fiber": 1.6,
    "description": "Cabbage, kimchi"
  },
  "170400": {
    "kcal": 42,
    "protein": 1.5,
    "fat": 0.3,
    "carb": 9.2,
    "fiber": 1.8,
    "description": "Celeriac, raw"
  },
  "170416": {
    "kcal": 36,
    "protein": 2.97,
    "fat": 0.79,
    "carb": 6.33,
    "fiber": 3.3,
    "description": "Parsley, fresh"
  },
  "170417": {
    "kcal": 75,
    "protein": 1.2,
    "fat": 0.3,
    "carb": 18,
    "fiber": 4.9,
    "description": "Parsnips, raw"
  },
  "170425": {
    "kcal": 53,
    "protein": 3.4,
    "fat": 0.47,
    "carb": 11.2,
    "fiber": 3.4,
    "description": "Peas and carrots, frozen, unprepared"
  },
  "170427": {
    "kcal": 20,
    "protein": 0.86,
    "fat": 0.17,
    "carb": 4.64,
    "fiber": 1.7,
    "description": "Peppers, sweet, green, raw"
  },
  "170431": {
    "kcal": 112,
    "protein": 0.38,
    "fat": 0.14,
    "carb": 27.2,
    "fiber": 0.4,
    "description": "Poi"
  },
  "170435": {
    "kcal": 87,
    "protein": 2.3,
    "fat": 0.15,
    "carb": 19.6,
    "fiber": 1.8,
    "description": "Potatoes, red, flesh and skin, baked"
  },
  "170461": {
    "kcal": 302,
    "protein": 12.9,
    "fat": 0.44,
    "carb": 74.7,
    "fiber": 16.5,
    "description": "Tomato powder"
  },
  "170463": {
    "kcal": 32,
    "protein": 1.32,
    "fat": 0.39,
    "carb": 7.09,
    "fiber": 1.4,
    "description": "Tomato products, canned, sauce, with tomato tidbits"
  },
  "170470": {
    "kcal": 21,
    "protein": 2.46,
    "fat": 0.19,
    "carb": 3.39,
    "fiber": 2.4,
    "description": "Turnip greens and turnips, frozen, unprepared"
  },
  "170471": {
    "kcal": 72,
    "protein": 3.33,
    "fat": 0.52,
    "carb": 13.5,
    "fiber": 4,
    "description": "Vegetables, mixed, frozen, unprepared"
  },
  "170483": {
    "kcal": 37,
    "protein": 2.1,
    "fat": 0.2,
    "carb": 8.53,
    "fiber": 3.2,
    "description": "Drumstick pods, raw"
  },
  "170492": {
    "kcal": 131,
    "protein": 4.42,
    "fat": 5.04,
    "carb": 17,
    "fiber": 1.2,
    "description": "Corn pudding, home prepared"
  },
  "170494": {
    "kcal": 172,
    "protein": 7.89,
    "fat": 13,
    "carb": 5.9,
    "fiber": 0.7,
    "description": "Spinach souffle"
  },
  "170497": {
    "kcal": 40,
    "protein": 2,
    "fat": 0.2,
    "carb": 9.46,
    "fiber": 1.5,
    "description": "Peppers, hot chili, green, raw"
  },
  "170499": {
    "kcal": 72,
    "protein": 2.5,
    "fat": 0.1,
    "carb": 16.8,
    "fiber": 3.2,
    "description": "Shallots, raw"
  },
  "170500": {
    "kcal": 341,
    "protein": 8.1,
    "fat": 1.49,
    "carb": 79.6,
    "fiber": 23.6,
    "description": "Carrot, dehydrated"
  },
  "170578": {
    "kcal": 443,
    "protein": 3.35,
    "fat": 31.7,
    "carb": 40.9,
    "fiber": 4.5,
    "description": "Nuts, coconut meat, dried (desiccated), sweetened, flaked, canned"
  },
  "170591": {
    "kcal": 673,
    "protein": 13.7,
    "fat": 68.4,
    "carb": 13.1,
    "fiber": 3.7,
    "description": "Nuts, pine nuts, dried"
  },
  "170602": {
    "kcal": 250,
    "protein": 27.1,
    "fat": 14.9,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, cured, corned beef, canned"
  },
  "170645": {
    "kcal": 242,
    "protein": 0.7,
    "fat": 0.2,
    "carb": 64.4,
    "fiber": 0.3,
    "description": "Jams and preserves, apricot"
  },
  "170674": {
    "kcal": 399,
    "protein": 0,
    "fat": 0,
    "carb": 99.8,
    "fiber": 0,
    "description": "Sugar, turbinado"
  },
  "170684": {
    "kcal": 357,
    "protein": 0.3,
    "fat": 0.1,
    "carb": 88.2,
    "fiber": 3.4,
    "description": "Arrowroot flour"
  },
  "170688": {
    "kcal": 342,
    "protein": 12.3,
    "fat": 1.33,
    "carb": 75.9,
    "fiber": 12.5,
    "description": "Bulgur, dry"
  },
  "170689": {
    "kcal": 226,
    "protein": 8.86,
    "fat": 12.7,
    "carb": 19.8,
    "fiber": 3.9,
    "description": "Fast foods, taco with beef, cheese and lettuce, hard shell"
  },
  "170722": {
    "kcal": 213,
    "protein": 12.6,
    "fat": 10.6,
    "carb": 16.8,
    "fiber": 1.3,
    "description": "WENDY'S, CLASSIC SINGLE Hamburger, no cheese"
  },
  "170845": {
    "kcal": 299,
    "protein": 22.2,
    "fat": 22.1,
    "carb": 2.4,
    "fiber": 0,
    "description": "Cheese, mozzarella, whole milk"
  },
  "170857": {
    "kcal": 195,
    "protein": 2.96,
    "fat": 19.1,
    "carb": 3.66,
    "fiber": 0,
    "description": "Cream, fluid, light (coffee cream or table cream)"
  },
  "170860": {
    "kcal": 257,
    "protein": 3.2,
    "fat": 22.2,
    "carb": 12.5,
    "fiber": 0,
    "description": "Cream, whipped, cream topping, pressurized"
  },
  "170865": {
    "kcal": 577,
    "protein": 4.9,
    "fat": 39.9,
    "carb": 52.5,
    "fiber": 0,
    "description": "Dessert topping, powdered"
  },
  "170887": {
    "kcal": 56,
    "protein": 5.73,
    "fat": 0.18,
    "carb": 7.68,
    "fiber": 0,
    "description": "Yogurt, plain, skim milk"
  },
  "170914": {
    "kcal": 82,
    "protein": 7.23,
    "fat": 0.24,
    "carb": 12.8,
    "fiber": 0.5,
    "description": "Yogurt, Greek, Blueberry, CHOBANI"
  },
  "170917": {
    "kcal": 313,
    "protein": 7.61,
    "fat": 8.36,
    "carb": 75,
    "fiber": 26.3,
    "description": "Spices, bay leaf"
  },
  "170918": {
    "kcal": 333,
    "protein": 19.8,
    "fat": 14.6,
    "carb": 49.9,
    "fiber": 38,
    "description": "Spices, caraway seed"
  },
  "170919": {
    "kcal": 311,
    "protein": 10.8,
    "fat": 6.7,
    "carb": 68.5,
    "fiber": 28,
    "description": "Spices, cardamom"
  },
  "170922": {
    "kcal": 298,
    "protein": 12.4,
    "fat": 17.8,
    "carb": 55,
    "fiber": 41.9,
    "description": "Spices, coriander seed"
  },
  "170923": {
    "kcal": 375,
    "protein": 17.8,
    "fat": 22.3,
    "carb": 44.2,
    "fiber": 10.5,
    "description": "Spices, cumin seed"
  },
  "170924": {
    "kcal": 325,
    "protein": 14.3,
    "fat": 14,
    "carb": 55.8,
    "fiber": 53.2,
    "description": "Spices, curry powder"
  },
  "170928": {
    "kcal": 271,
    "protein": 12.7,
    "fat": 7.04,
    "carb": 60.6,
    "fiber": 40.3,
    "description": "Spices, marjoram, dried"
  },
  "170929": {
    "kcal": 508,
    "protein": 26.1,
    "fat": 36.2,
    "carb": 28.1,
    "fiber": 12.2,
    "description": "Spices, mustard seed, ground"
  },
  "170931": {
    "kcal": 251,
    "protein": 10.4,
    "fat": 3.26,
    "carb": 64,
    "fiber": 25.3,
    "description": "Spices, pepper, black"
  },
  "170932": {
    "kcal": 318,
    "protein": 12,
    "fat": 17.3,
    "carb": 56.6,
    "fiber": 27.2,
    "description": "Spices, pepper, red or cayenne"
  },
  "170934": {
    "kcal": 310,
    "protein": 11.4,
    "fat": 5.85,
    "carb": 65.4,
    "fiber": 3.9,
    "description": "Spices, saffron"
  },
  "170935": {
    "kcal": 315,
    "protein": 10.6,
    "fat": 12.8,
    "carb": 60.7,
    "fiber": 40.3,
    "description": "Spices, sage, ground"
  },
  "170937": {
    "kcal": 295,
    "protein": 22.8,
    "fat": 7.24,
    "carb": 50.2,
    "fiber": 7.4,
    "description": "Spices, tarragon, dried"
  },
  "170963": {
    "kcal": 48,
    "protein": 0.5,
    "fat": 0.1,
    "carb": 11.7,
    "fiber": 0.1,
    "description": "Babyfood, juice, orange and pineapple"
  },
  "170977": {
    "kcal": 79,
    "protein": 0.2,
    "fat": 0.16,
    "carb": 19.2,
    "fiber": 1.4,
    "description": "Babyfood, dessert, dutch apple, junior"
  },
  "171005": {
    "kcal": 355,
    "protein": 0.69,
    "fat": 26.2,
    "carb": 31.9,
    "fiber": 0.7,
    "description": "Salad dressing, russian dressing"
  },
  "171015": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, palm"
  },
  "171027": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, safflower, salad or cooking, high oleic (primary safflower oil of commerce)"
  },
  "171030": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, walnut"
  },
  "171112": {
    "kcal": 217,
    "protein": 26.8,
    "fat": 11.4,
    "carb": 0,
    "fiber": 0,
    "description": "Duck, young duckling, domesticated, White Pekin, leg, meat and skin, bone in, cooked, roasted"
  },
  "171181": {
    "kcal": 57,
    "protein": 3.3,
    "fat": 0.88,
    "carb": 10.5,
    "fiber": 2.6,
    "description": "SMART SOUP, Indian Bean Masala"
  },
  "171183": {
    "kcal": 36,
    "protein": 0.8,
    "fat": 1.06,
    "carb": 6.5,
    "fiber": 1,
    "description": "SMART SOUP, Thai Coconut Curry"
  },
  "171184": {
    "kcal": 44,
    "protein": 1.3,
    "fat": 1.06,
    "carb": 8.2,
    "fiber": 1.5,
    "description": "SMART SOUP, Vietnamese Carrot Lemongrass"
  },
  "171186": {
    "kcal": 93,
    "protein": 1.93,
    "fat": 0.93,
    "carb": 19.2,
    "fiber": 2.2,
    "description": "Sauce, hot chile, sriracha"
  },
  "171188": {
    "kcal": 79,
    "protein": 1.86,
    "fat": 0.9,
    "carb": 15.9,
    "fiber": 2.2,
    "description": "Sauce, hot chile, sriracha, TUONG OT SRIRACHA"
  },
  "171241": {
    "kcal": 356,
    "protein": 24.9,
    "fat": 27.4,
    "carb": 2.22,
    "fiber": 0,
    "description": "Cheese, gouda"
  },
  "171242": {
    "kcal": 413,
    "protein": 29.8,
    "fat": 32.3,
    "carb": 0.36,
    "fiber": 0,
    "description": "Cheese, gruyere"
  },
  "171247": {
    "kcal": 420,
    "protein": 28.4,
    "fat": 27.8,
    "carb": 13.9,
    "fiber": 0,
    "description": "Cheese, parmesan, grated"
  },
  "171249": {
    "kcal": 387,
    "protein": 31.8,
    "fat": 26.9,
    "carb": 3.63,
    "fiber": 0,
    "description": "Cheese, romano"
  },
  "171257": {
    "kcal": 198,
    "protein": 2.44,
    "fat": 19.4,
    "carb": 4.63,
    "fiber": 0,
    "description": "Cream, sour, cultured"
  },
  "171275": {
    "kcal": 321,
    "protein": 7.91,
    "fat": 8.7,
    "carb": 54.4,
    "fiber": 0,
    "description": "Milk, canned, condensed, sweetened"
  },
  "171288": {
    "kcal": 384,
    "protein": 23.5,
    "fat": 32.1,
    "carb": 0.13,
    "fiber": 0,
    "description": "Cheese, Mexican blend"
  },
  "171314": {
    "kcal": 900,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Butter, Clarified butter (ghee)"
  },
  "171315": {
    "kcal": 263,
    "protein": 6.09,
    "fat": 8.69,
    "carb": 72.1,
    "fiber": 21.6,
    "description": "Spices, allspice, ground"
  },
  "171316": {
    "kcal": 337,
    "protein": 17.6,
    "fat": 15.9,
    "carb": 50,
    "fiber": 14.6,
    "description": "Spices, anise seed"
  },
  "171319": {
    "kcal": 282,
    "protein": 13.5,
    "fat": 14.3,
    "carb": 49.7,
    "fiber": 34.8,
    "description": "Spices, chili powder"
  },
  "171321": {
    "kcal": 274,
    "protein": 5.97,
    "fat": 13,
    "carb": 65.5,
    "fiber": 33.9,
    "description": "Spices, cloves, ground"
  },
  "171322": {
    "kcal": 253,
    "protein": 20,
    "fat": 4.36,
    "carb": 55.8,
    "fiber": 13.6,
    "description": "Spices, dill weed, dried"
  },
  "171323": {
    "kcal": 345,
    "protein": 15.8,
    "fat": 14.9,
    "carb": 52.3,
    "fiber": 39.8,
    "description": "Spices, fennel seed"
  },
  "171324": {
    "kcal": 323,
    "protein": 23,
    "fat": 6.41,
    "carb": 58.4,
    "fiber": 24.6,
    "description": "Spices, fenugreek seed"
  },
  "171325": {
    "kcal": 331,
    "protein": 16.6,
    "fat": 0.73,
    "carb": 72.7,
    "fiber": 9,
    "description": "Spices, garlic powder"
  },
  "171328": {
    "kcal": 265,
    "protein": 9,
    "fat": 4.28,
    "carb": 68.9,
    "fiber": 42.5,
    "description": "Spices, oregano, dried"
  },
  "171329": {
    "kcal": 282,
    "protein": 14.1,
    "fat": 12.9,
    "carb": 54,
    "fiber": 34.9,
    "description": "Spices, paprika"
  },
  "171330": {
    "kcal": 525,
    "protein": 18,
    "fat": 41.6,
    "carb": 28.1,
    "fiber": 19.5,
    "description": "Spices, poppy seed"
  },
  "171332": {
    "kcal": 342,
    "protein": 5.76,
    "fat": 12.6,
    "carb": 69.3,
    "fiber": 14.8,
    "description": "Spices, pumpkin pie spice"
  },
  "171352": {
    "kcal": 43,
    "protein": 0.2,
    "fat": 0.1,
    "carb": 10.5,
    "fiber": 0.1,
    "description": "Babyfood, juice, apple and peach"
  },
  "171354": {
    "kcal": 45,
    "protein": 0.6,
    "fat": 0.3,
    "carb": 10.2,
    "fiber": 0.1,
    "description": "Babyfood, juice, orange"
  },
  "171357": {
    "kcal": 47,
    "protein": 0.1,
    "fat": 0.1,
    "carb": 11.7,
    "fiber": 0.1,
    "description": "Babyfood, juice, mixed fruit"
  },
  "171370": {
    "kcal": 397,
    "protein": 10.8,
    "fat": 2,
    "carb": 82.2,
    "fiber": 2.3,
    "description": "Babyfood, pretzels"
  },
  "171401": {
    "kcal": 902,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Lard"
  },
  "171412": {
    "kcal": 892,
    "protein": 0,
    "fat": 99.1,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, coconut"
  },
  "171421": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, cocoa butter"
  },
  "171427": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, hazelnut"
  },
  "171515": {
    "kcal": 263,
    "protein": 14.7,
    "fat": 15.8,
    "carb": 15,
    "fiber": 1.1,
    "description": "Chicken breast tenders, breaded, uncooked"
  },
  "171560": {
    "kcal": 213,
    "protein": 16,
    "fat": 8.89,
    "carb": 17.4,
    "fiber": 0,
    "description": "Soup, beef broth or bouillon, powder, dry"
  },
  "171577": {
    "kcal": 53,
    "protein": 2.9,
    "fat": 1.06,
    "carb": 9.5,
    "fiber": 2.9,
    "description": "SMART SOUP, French Lentil"
  },
  "171584": {
    "kcal": 438,
    "protein": 7.68,
    "fat": 18.3,
    "carb": 60.5,
    "fiber": 1,
    "description": "Sauce, cheese sauce mix, dry"
  },
  "171589": {
    "kcal": 369,
    "protein": 9.8,
    "fat": 9.48,
    "carb": 61.1,
    "fiber": 4.3,
    "description": "Gravy, instant beef, dry"
  },
  "171604": {
    "kcal": 21,
    "protein": 0.9,
    "fat": 0.6,
    "carb": 3.9,
    "fiber": 0.7,
    "description": "Sauce, peppers, hot, chili, mature red, canned"
  },
  "171610": {
    "kcal": 77,
    "protein": 0,
    "fat": 0,
    "carb": 19.2,
    "fiber": 0,
    "description": "Sauce, worcestershire"
  },
  "171613": {
    "kcal": 438,
    "protein": 16.7,
    "fat": 13.9,
    "carb": 64.9,
    "fiber": 0.2,
    "description": "Soup, bouillon cubes and granules, low sodium, dry"
  },
  "171618": {
    "kcal": 379,
    "protein": 14.6,
    "fat": 34.5,
    "carb": 1.29,
    "fiber": 0,
    "description": "Blood sausage"
  },
  "171623": {
    "kcal": 328,
    "protein": 14.1,
    "fat": 29,
    "carb": 1.51,
    "fiber": 0,
    "description": "Cheesefurter, cheese smokie, pork, beef"
  },
  "171647": {
    "kcal": 361,
    "protein": 11.2,
    "fat": 1.81,
    "carb": 80.5,
    "fiber": 13,
    "description": "Cereals ready-to-eat, POST, GRAPE-NUTS Cereal"
  },
  "171656": {
    "kcal": 343,
    "protein": 7.31,
    "fat": 2.14,
    "carb": 78.4,
    "fiber": 4.2,
    "description": "Cereals, QUAKER, corn grits, instant, plain, dry"
  },
  "171697": {
    "kcal": 48,
    "protein": 1.4,
    "fat": 0.39,
    "carb": 11.1,
    "fiber": 2,
    "description": "Apricots, raw"
  },
  "171708": {
    "kcal": 333,
    "protein": 1.25,
    "fat": 0.73,
    "carb": 80.4,
    "fiber": 2.5,
    "description": "Cherries, tart, dried, sweetened (Includes foods for USDA's Food Distribution Program)"
  },
  "171714": {
    "kcal": 103,
    "protein": 1.07,
    "fat": 0.23,
    "carb": 27.1,
    "fiber": 4.9,
    "description": "Breadfruit, raw"
  },
  "171719": {
    "kcal": 63,
    "protein": 1.06,
    "fat": 0.2,
    "carb": 16,
    "fiber": 2.1,
    "description": "Cherries, sweet, raw"
  },
  "171722": {
    "kcal": 46,
    "protein": 0.46,
    "fat": 0.13,
    "carb": 12,
    "fiber": 3.6,
    "description": "Cranberries, raw"
  },
  "171723": {
    "kcal": 308,
    "protein": 0.17,
    "fat": 1.09,
    "carb": 82.8,
    "fiber": 5.3,
    "description": "Cranberries, dried, sweetened (Includes foods for USDA's Food Distribution Program)"
  },
  "171724": {
    "kcal": 290,
    "protein": 3.43,
    "fat": 0.22,
    "carb": 77,
    "fiber": 4.4,
    "description": "Currants, zante, dried"
  },
  "171821": {
    "kcal": 32,
    "protein": 2.08,
    "fat": 0.26,
    "carb": 5.25,
    "fiber": 0.2,
    "description": "Soup, wonton, Chinese restaurant"
  },
  "171823": {
    "kcal": 245,
    "protein": 0.36,
    "fat": 0.13,
    "carb": 60.7,
    "fiber": 0.6,
    "description": "Sauce, duck, ready-to-serve"
  },
  "171842": {
    "kcal": 398,
    "protein": 2.61,
    "fat": 18.3,
    "carb": 55.6,
    "fiber": 2.6,
    "description": "Cookies, oatmeal sandwich, with creme filling"
  },
  "171845": {
    "kcal": 291,
    "protein": 9.62,
    "fat": 5.65,
    "carb": 50.4,
    "fiber": 2.2,
    "description": "Bread, naan, plain, commercially prepared, refrigerated"
  },
  "171849": {
    "kcal": 253,
    "protein": 7.05,
    "fat": 5.29,
    "carb": 44.4,
    "fiber": 3.5,
    "description": "Bread, cinnamon"
  },
  "171861": {
    "kcal": 310,
    "protein": 7.99,
    "fat": 6.4,
    "carb": 55.1,
    "fiber": 3.6,
    "description": "Rolls, gluten-free, white, made with brown rice flour, tapioca starch, and potato starch"
  },
  "171862": {
    "kcal": 239,
    "protein": 3.34,
    "fat": 2.65,
    "carb": 50.5,
    "fiber": 5.1,
    "description": "Rolls, gluten-free, white, made with rice flour, rice starch, and corn starch"
  },
  "171866": {
    "kcal": 447,
    "protein": 10,
    "fat": 22.5,
    "carb": 51.1,
    "fiber": 5,
    "description": "Cookies, chocolate cream covered biscuit sticks"
  },
  "171882": {
    "kcal": 48,
    "protein": 0.6,
    "fat": 0.2,
    "carb": 11,
    "fiber": 0.4,
    "description": "Beverages, Clam and tomato juice, canned"
  },
  "171942": {
    "kcal": 47,
    "protein": 0.28,
    "fat": 0.97,
    "carb": 9.17,
    "fiber": 0.3,
    "description": "Beverages, rice milk, unsweetened"
  },
  "171967": {
    "kcal": 155,
    "protein": 20.2,
    "fat": 7.52,
    "carb": 0.48,
    "fiber": 0,
    "description": "Crustaceans, crab, blue, crab cakes, home recipe"
  },
  "172065": {
    "kcal": 282,
    "protein": 15.5,
    "fat": 16.1,
    "carb": 18.8,
    "fiber": 0.8,
    "description": "McDONALD'S, Double Cheeseburger"
  },
  "172079": {
    "kcal": 403,
    "protein": 7.02,
    "fat": 18,
    "carb": 53.4,
    "fiber": 2.2,
    "description": "Fast foods, miniature cinnamon rolls"
  },
  "172177": {
    "kcal": 334,
    "protein": 20.8,
    "fat": 27.7,
    "carb": 0.45,
    "fiber": 0,
    "description": "Cheese, brie"
  },
  "172194": {
    "kcal": 134,
    "protein": 6.81,
    "fat": 7.56,
    "carb": 10,
    "fiber": 0,
    "description": "Milk, canned, evaporated, with added vitamin A"
  },
  "172197": {
    "kcal": 452,
    "protein": 30.5,
    "fat": 35.6,
    "carb": 2.17,
    "fiber": 0,
    "description": "Cheese, goat, hard type"
  },
  "172223": {
    "kcal": 299,
    "protein": 18.1,
    "fat": 23.8,
    "carb": 2.98,
    "fiber": 0,
    "description": "Cheese, fresh, queso fresco"
  },
  "172226": {
    "kcal": 237,
    "protein": 4.29,
    "fat": 8.57,
    "carb": 37.1,
    "fiber": 0,
    "description": "Ice cream sandwich"
  },
  "172231": {
    "kcal": 312,
    "protein": 9.68,
    "fat": 3.25,
    "carb": 67.1,
    "fiber": 22.7,
    "description": "Spices, turmeric, ground"
  },
  "172232": {
    "kcal": 23,
    "protein": 3.15,
    "fat": 0.64,
    "carb": 2.65,
    "fiber": 1.6,
    "description": "Basil, fresh"
  },
  "172238": {
    "kcal": 23,
    "protein": 2.36,
    "fat": 0.86,
    "carb": 4.89,
    "fiber": 3.2,
    "description": "Capers, canned"
  },
  "172239": {
    "kcal": 285,
    "protein": 19.9,
    "fat": 6.03,
    "carb": 52,
    "fiber": 29.8,
    "description": "Spearmint, dried"
  },
  "172240": {
    "kcal": 19,
    "protein": 0.04,
    "fat": 0,
    "carb": 0.27,
    "fiber": 0,
    "description": "Vinegar, red wine"
  },
  "172241": {
    "kcal": 88,
    "protein": 0.49,
    "fat": 0,
    "carb": 17,
    "fiber": 0,
    "description": "Vinegar, balsamic"
  },
  "172259": {
    "kcal": 82,
    "protein": 3.5,
    "fat": 2.6,
    "carb": 11.2,
    "fiber": 0.5,
    "description": "Babyfood, macaroni and cheese, toddler"
  },
  "172275": {
    "kcal": 24,
    "protein": 0.81,
    "fat": 0.2,
    "carb": 5.73,
    "fiber": 0.9,
    "description": "Babyfood, vegetables, squash, junior"
  },
  "172284": {
    "kcal": 32,
    "protein": 2.3,
    "fat": 0.2,
    "carb": 6.8,
    "fiber": 1.5,
    "description": "Babyfood, vegetables, garden vegetable, strained"
  },
  "172335": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, nutmeg butter"
  },
  "172336": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, canola"
  },
  "172337": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, mustard"
  },
  "172340": {
    "kcal": 902,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Fish oil, herring"
  },
  "172343": {
    "kcal": 902,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Fish oil, salmon"
  },
  "172357": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, industrial, mid-oleic, sunflower"
  },
  "172363": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, industrial, soy (partially hydrogenated ) and soy (winterized), pourable clear fry"
  },
  "172370": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, vegetable, soybean, refined"
  },
  "172378": {
    "kcal": 214,
    "protein": 16.4,
    "fat": 16,
    "carb": 0.17,
    "fiber": 0,
    "description": "Chicken, broilers or fryers, leg, meat and skin, raw"
  },
  "172428": {
    "kcal": 364,
    "protein": 23.1,
    "fat": 3.89,
    "carb": 61.6,
    "fiber": 22.2,
    "description": "Peas, green, split, mature seeds, raw"
  },
  "172431": {
    "kcal": 579,
    "protein": 28,
    "fat": 49,
    "carb": 17.4,
    "fiber": 8.9,
    "description": "Peanuts, spanish, oil-roasted, with salt"
  },
  "172436": {
    "kcal": 343,
    "protein": 21.7,
    "fat": 1.49,
    "carb": 62.8,
    "fiber": 15,
    "description": "Pigeon peas (red gram), mature seeds, raw"
  },
  "172439": {
    "kcal": 309,
    "protein": 11.7,
    "fat": 29.5,
    "carb": 5.31,
    "fiber": 2.6,
    "description": "Bacon, meatless"
  },
  "172451": {
    "kcal": 270,
    "protein": 18.8,
    "fat": 20.2,
    "carb": 8.86,
    "fiber": 3.9,
    "description": "Tofu, fried"
  },
  "172455": {
    "kcal": 333,
    "protein": 13.3,
    "fat": 17.8,
    "carb": 31.8,
    "fiber": 0,
    "description": "Falafel, home-prepared"
  },
  "172461": {
    "kcal": 62,
    "protein": 6.9,
    "fat": 2.7,
    "carb": 2.4,
    "fiber": 0.1,
    "description": "MORI-NU, Tofu, silken, firm"
  },
  "172513": {
    "kcal": 183,
    "protein": 20.1,
    "fat": 11.4,
    "carb": 0.09,
    "fiber": 0,
    "description": "Lamb, New Zealand, imported, fore-shank, separable lean and fat, raw"
  },
  "172517": {
    "kcal": 298,
    "protein": 15.4,
    "fat": 26.2,
    "carb": 0.22,
    "fiber": 0,
    "description": "Lamb, New Zealand, imported, loin chop, separable lean and fat, raw"
  },
  "172568": {
    "kcal": 113,
    "protein": 19.2,
    "fat": 3.48,
    "carb": 0,
    "fiber": 0,
    "description": "Veal, shank (fore and hind), separable lean and fat, raw"
  },
  "172617": {
    "kcal": 193,
    "protein": 20.3,
    "fat": 12.4,
    "carb": 0,
    "fiber": 0,
    "description": "Lamb, New Zealand, imported, ground lamb, raw"
  },
  "172643": {
    "kcal": 107,
    "protein": 22.1,
    "fat": 2.07,
    "carb": 0,
    "fiber": 0,
    "description": "Veal, leg, top round, cap off, cutlet, boneless, raw"
  },
  "172671": {
    "kcal": 263,
    "protein": 6.1,
    "fat": 5.6,
    "carb": 47.4,
    "fiber": 0,
    "description": "Biscuits, mixed grain, refrigerated dough"
  },
  "172674": {
    "kcal": 315,
    "protein": 10.5,
    "fat": 6.6,
    "carb": 52.6,
    "fiber": 2.5,
    "description": "Bread, egg, toasted"
  },
  "172678": {
    "kcal": 269,
    "protein": 8.4,
    "fat": 4.4,
    "carb": 48.5,
    "fiber": 4,
    "description": "Bread, oatmeal"
  },
  "172684": {
    "kcal": 259,
    "protein": 8.5,
    "fat": 3.3,
    "carb": 48.3,
    "fiber": 5.8,
    "description": "Bread, rye"
  },
  "172749": {
    "kcal": 427,
    "protein": 10.6,
    "fat": 14.1,
    "carb": 69.6,
    "fiber": 10.3,
    "description": "Crackers, whole-wheat"
  },
  "172751": {
    "kcal": 407,
    "protein": 11.9,
    "fat": 6.6,
    "carb": 73.5,
    "fiber": 5.1,
    "description": "Croutons, plain"
  },
  "172752": {
    "kcal": 465,
    "protein": 10.8,
    "fat": 18.3,
    "carb": 63.5,
    "fiber": 5,
    "description": "Croutons, seasoned"
  },
  "172761": {
    "kcal": 223,
    "protein": 8.7,
    "fat": 2,
    "carb": 44.8,
    "fiber": 4.6,
    "description": "Muffins, English, wheat"
  },
  "172785": {
    "kcal": 268,
    "protein": 1.5,
    "fat": 8.7,
    "carb": 47.2,
    "fiber": 1.2,
    "description": "Pie, lemon meringue, commercially prepared"
  },
  "172790": {
    "kcal": 551,
    "protein": 7.3,
    "fat": 38.1,
    "carb": 45.1,
    "fiber": 1.5,
    "description": "Puff pastry, frozen, ready-to-bake"
  },
  "172791": {
    "kcal": 299,
    "protein": 7.1,
    "fat": 6,
    "carb": 52.6,
    "fiber": 1.9,
    "description": "Phyllo dough"
  },
  "172802": {
    "kcal": 291,
    "protein": 9.8,
    "fat": 1.5,
    "carb": 57.9,
    "fiber": 1.8,
    "description": "Wonton wrappers (includes egg roll wrappers)"
  },
  "172805": {
    "kcal": 97,
    "protein": 0.1,
    "fat": 0.4,
    "carb": 46.9,
    "fiber": 2.2,
    "description": "Leavening agents, baking powder, low-sodium"
  },
  "172855": {
    "kcal": 440,
    "protein": 9.58,
    "fat": 44.2,
    "carb": 0.79,
    "fiber": 0,
    "description": "Chicken, skin (drumsticks and thighs), raw"
  },
  "172879": {
    "kcal": 184,
    "protein": 0.89,
    "fat": 1.04,
    "carb": 42.8,
    "fiber": 0.7,
    "description": "Sauce, plum, ready-to-serve"
  },
  "172883": {
    "kcal": 13,
    "protein": 1.97,
    "fat": 0.09,
    "carb": 1.2,
    "fiber": 0,
    "description": "Soup, stock, beef, home-prepared"
  },
  "172884": {
    "kcal": 36,
    "protein": 2.52,
    "fat": 1.2,
    "carb": 3.53,
    "fiber": 0,
    "description": "Soup, stock, chicken, home-prepared"
  },
  "172885": {
    "kcal": 16,
    "protein": 2.26,
    "fat": 0.81,
    "carb": 0,
    "fiber": 0,
    "description": "Soup, stock, fish, home-prepared"
  },
  "172886": {
    "kcal": 220,
    "protein": 3.31,
    "fat": 3.39,
    "carb": 44.1,
    "fiber": 2.8,
    "description": "Sauce, hoisin, ready-to-serve"
  },
  "172926": {
    "kcal": 235,
    "protein": 11.8,
    "fat": 16.5,
    "carb": 9.2,
    "fiber": 0,
    "description": "Olive loaf, pork"
  },
  "172928": {
    "kcal": 201,
    "protein": 13.4,
    "fat": 13.1,
    "carb": 6.55,
    "fiber": 0,
    "description": "Pate, chicken liver, canned"
  },
  "172946": {
    "kcal": 180,
    "protein": 16.3,
    "fat": 11.2,
    "carb": 3.65,
    "fiber": 0,
    "description": "Oscar Mayer, Ham (chopped with natural juice)"
  },
  "172967": {
    "kcal": 327,
    "protein": 11.2,
    "fat": 28.5,
    "carb": 6.3,
    "fiber": 0,
    "description": "Pate, truffle flavor"
  },
  "173021": {
    "kcal": 74,
    "protein": 0.75,
    "fat": 0.3,
    "carb": 19.2,
    "fiber": 2.9,
    "description": "Figs, raw"
  },
  "173032": {
    "kcal": 349,
    "protein": 14.3,
    "fat": 0.39,
    "carb": 77.1,
    "fiber": 13,
    "description": "Goji berries, dried"
  },
  "173085": {
    "kcal": 178,
    "protein": 27.5,
    "fat": 7.58,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, New Zealand, imported, knuckle, cooked, fast fried"
  },
  "173098": {
    "kcal": 159,
    "protein": 21.3,
    "fat": 8.22,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, New Zealand, imported, bolar blade, separable lean and fat, raw"
  },
  "173105": {
    "kcal": 147,
    "protein": 20.6,
    "fat": 7.2,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, New Zealand, imported, hind shin, separable lean and fat, raw"
  },
  "173161": {
    "kcal": 416,
    "protein": 10,
    "fat": 5,
    "carb": 82.6,
    "fiber": 0,
    "description": "Rice crackers"
  },
  "173203": {
    "kcal": 43,
    "protein": 0,
    "fat": 0,
    "carb": 11.2,
    "fiber": 0,
    "description": "Beverages, carbonated, grape soda"
  },
  "173236": {
    "kcal": 49,
    "protein": 0,
    "fat": 0,
    "carb": 12.6,
    "fiber": 0.1,
    "description": "Beverages, orange-flavor drink, breakfast type, powder, prepared with water"
  },
  "173261": {
    "kcal": 243,
    "protein": 8.59,
    "fat": 2.88,
    "carb": 46.4,
    "fiber": 2.6,
    "description": "Pillsbury, Crusty French Loaf, refrigerated dough"
  },
  "173405": {
    "kcal": 336,
    "protein": 15.8,
    "fat": 29.9,
    "carb": 0.9,
    "fiber": 0,
    "description": "Beef, rib, back ribs, bone-in, separable lean and fat, trimmed to 0\" fat, choice, raw"
  },
  "173410": {
    "kcal": 717,
    "protein": 0.85,
    "fat": 81.1,
    "carb": 0.06,
    "fiber": 0,
    "description": "Butter, salted"
  },
  "173416": {
    "kcal": 394,
    "protein": 23.8,
    "fat": 32.1,
    "carb": 2.57,
    "fiber": 0,
    "description": "Cheese, colby"
  },
  "173418": {
    "kcal": 350,
    "protein": 6.15,
    "fat": 34.4,
    "carb": 5.52,
    "fiber": 0,
    "description": "Cheese, cream"
  },
  "173420": {
    "kcal": 265,
    "protein": 14.2,
    "fat": 21.5,
    "carb": 3.88,
    "fiber": 0,
    "description": "Cheese, feta"
  },
  "173428": {
    "kcal": 669,
    "protein": 33.6,
    "fat": 59.1,
    "carb": 0.66,
    "fiber": 0,
    "description": "Egg, yolk, dried"
  },
  "173461": {
    "kcal": 315,
    "protein": 6.84,
    "fat": 7.35,
    "carb": 55.4,
    "fiber": 0,
    "description": "Dulce de Leche"
  },
  "173469": {
    "kcal": 21,
    "protein": 0,
    "fat": 0,
    "carb": 0.93,
    "fiber": 0,
    "description": "Vinegar, cider"
  },
  "173470": {
    "kcal": 101,
    "protein": 5.56,
    "fat": 1.68,
    "carb": 24.4,
    "fiber": 14,
    "description": "Thyme, fresh"
  },
  "173471": {
    "kcal": 288,
    "protein": 0.06,
    "fat": 0.06,
    "carb": 12.6,
    "fiber": 0,
    "description": "Vanilla extract"
  },
  "173472": {
    "kcal": 48,
    "protein": 1.18,
    "fat": 0.69,
    "carb": 11.3,
    "fiber": 3.3,
    "description": "Horseradish, prepared"
  },
  "173473": {
    "kcal": 131,
    "protein": 3.31,
    "fat": 5.86,
    "carb": 20.7,
    "fiber": 14.1,
    "description": "Rosemary, fresh"
  },
  "173486": {
    "kcal": 184,
    "protein": 13.4,
    "fat": 14.6,
    "carb": 1.1,
    "fiber": 0.2,
    "description": "Babyfood, meat, meat sticks, junior"
  },
  "173491": {
    "kcal": 59,
    "protein": 2.5,
    "fat": 1.1,
    "carb": 9.4,
    "fiber": 1.1,
    "description": "Babyfood, dinner, macaroni and tomato and beef, junior"
  },
  "173517": {
    "kcal": 62,
    "protein": 2.6,
    "fat": 0.9,
    "carb": 10.9,
    "fiber": 1.8,
    "description": "Babyfood, apples with ham, strained"
  },
  "173520": {
    "kcal": 380,
    "protein": 14.3,
    "fat": 4,
    "carb": 71.8,
    "fiber": 2.3,
    "description": "Babyfood, snack, GERBER, GRADUATES, YOGURT MELTS"
  },
  "173572": {
    "kcal": 900,
    "protein": 0,
    "fat": 99.8,
    "carb": 0,
    "fiber": 0,
    "description": "Fat, goose"
  },
  "173573": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, avocado"
  },
  "173576": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Oil, oat"
  },
  "173577": {
    "kcal": 902,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Fish oil, cod liver"
  },
  "173578": {
    "kcal": 902,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Fish oil, sardine"
  },
  "173584": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Shortening, vegetable, household, composite"
  },
  "173597": {
    "kcal": 884,
    "protein": 0,
    "fat": 100,
    "carb": 0,
    "fiber": 0,
    "description": "Shortening, industrial, soy (partially hydrogenated), pourable liquid fry shortening"
  },
  "173635": {
    "kcal": 223,
    "protein": 24,
    "fat": 13.4,
    "carb": 0,
    "fiber": 0,
    "description": "Chicken, roasting, meat and skin, cooked, roasted"
  },
  "173676": {
    "kcal": 76,
    "protein": 14.5,
    "fat": 1.52,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, monkfish, raw"
  },
  "173687": {
    "kcal": 117,
    "protein": 18.3,
    "fat": 4.32,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, salmon, chinook, smoked"
  },
  "173717": {
    "kcal": 141,
    "protein": 19.9,
    "fat": 6.18,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, trout, rainbow, farmed, raw"
  },
  "173720": {
    "kcal": 130,
    "protein": 26.3,
    "fat": 1.2,
    "carb": 1.7,
    "fiber": 0,
    "description": "Mollusks, conch, baked or broiled"
  },
  "173734": {
    "kcal": 341,
    "protein": 21.6,
    "fat": 1.42,
    "carb": 62.4,
    "fiber": 15.5,
    "description": "Beans, black, mature seeds, raw"
  },
  "173857": {
    "kcal": 209,
    "protein": 11.4,
    "fat": 16,
    "carb": 4.68,
    "fiber": 0.5,
    "description": "Bologna, turkey"
  },
  "173858": {
    "kcal": 158,
    "protein": 18,
    "fat": 17.6,
    "carb": 4.05,
    "fiber": 0.3,
    "description": "Chicken spread"
  },
  "173859": {
    "kcal": 296,
    "protein": 13.6,
    "fat": 25.1,
    "carb": 3.78,
    "fiber": 0,
    "description": "Sausage, pork, chorizo, link or ground, raw"
  },
  "173865": {
    "kcal": 263,
    "protein": 16.3,
    "fat": 20.7,
    "carb": 1.84,
    "fiber": 0,
    "description": "Ham, minced"
  },
  "173877": {
    "kcal": 337,
    "protein": 12.4,
    "fat": 29.7,
    "carb": 5.03,
    "fiber": 0,
    "description": "Kielbasa, fully cooked, grilled"
  },
  "173919": {
    "kcal": 395,
    "protein": 6.5,
    "fat": 5.3,
    "carb": 81.6,
    "fiber": 4.7,
    "description": "Cereals ready-to-eat, POST SELECTS Blueberry Morning"
  },
  "173941": {
    "kcal": 241,
    "protein": 3.39,
    "fat": 0.51,
    "carb": 62.6,
    "fiber": 7.3,
    "description": "Apricots, dried, sulfured, uncooked"
  },
  "173945": {
    "kcal": 346,
    "protein": 3.89,
    "fat": 1.81,
    "carb": 88.3,
    "fiber": 9.9,
    "description": "Bananas, dehydrated, or banana powder"
  },
  "173946": {
    "kcal": 43,
    "protein": 1.39,
    "fat": 0.49,
    "carb": 9.61,
    "fiber": 5.3,
    "description": "Blackberries, raw"
  },
  "173964": {
    "kcal": 56,
    "protein": 1.4,
    "fat": 0.2,
    "carb": 13.8,
    "fiber": 4.3,
    "description": "Currants, red and white, raw"
  },
  "174066": {
    "kcal": 154,
    "protein": 0.27,
    "fat": 0.02,
    "carb": 38.2,
    "fiber": 0.1,
    "description": "Sauce, sweet and sour, ready-to-serve"
  },
  "174068": {
    "kcal": 143,
    "protein": 3.14,
    "fat": 9.51,
    "carb": 11.1,
    "fiber": 0.7,
    "description": "Dip, salsa con queso, cheese and salsa- medium"
  },
  "174074": {
    "kcal": 30,
    "protein": 0.62,
    "fat": 0.91,
    "carb": 4.87,
    "fiber": 0.5,
    "description": "Sauce, enchilada, red, mild, ready to serve"
  },
  "174078": {
    "kcal": 318,
    "protein": 10.6,
    "fat": 5.8,
    "carb": 55.8,
    "fiber": 2.2,
    "description": "Bread, roll, Mexican, bollilo"
  },
  "174079": {
    "kcal": 503,
    "protein": 4.1,
    "fat": 23.5,
    "carb": 68.8,
    "fiber": 1.9,
    "description": "Cookie, butter or sugar, with chocolate icing or filling"
  },
  "174116": {
    "kcal": 31,
    "protein": 0.21,
    "fat": 2.08,
    "carb": 2.92,
    "fiber": 0,
    "description": "Beverages, coconut milk, sweetened, fortified with calcium, vitamins A, B12, D2"
  },
  "174122": {
    "kcal": 398,
    "protein": 6.67,
    "fat": 4,
    "carb": 83.7,
    "fiber": 3.7,
    "description": "Beverages, Cocoa mix, powder"
  },
  "174182": {
    "kcal": 131,
    "protein": 20.4,
    "fat": 4.84,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, anchovy, european, raw"
  },
  "174190": {
    "kcal": 290,
    "protein": 62.8,
    "fat": 2.37,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, cod, Atlantic, dried and salted"
  },
  "174199": {
    "kcal": 116,
    "protein": 25.2,
    "fat": 0.96,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, haddock, smoked"
  },
  "174208": {
    "kcal": 77,
    "protein": 16.5,
    "fat": 0.75,
    "carb": 0,
    "fiber": 0,
    "description": "Crustaceans, lobster, northern, raw"
  },
  "174216": {
    "kcal": 86,
    "protein": 11.9,
    "fat": 2.24,
    "carb": 3.69,
    "fiber": 0,
    "description": "Mollusks, mussel, blue, raw"
  },
  "174223": {
    "kcal": 92,
    "protein": 15.6,
    "fat": 1.38,
    "carb": 3.08,
    "fiber": 0,
    "description": "Mollusks, squid, mixed species, raw"
  },
  "174256": {
    "kcal": 347,
    "protein": 23.9,
    "fat": 1.15,
    "carb": 62.6,
    "fiber": 16.3,
    "description": "Mung beans, mature seeds, raw"
  },
  "174258": {
    "kcal": 351,
    "protein": 0.16,
    "fat": 0.06,
    "carb": 86.1,
    "fiber": 0.5,
    "description": "Noodles, chinese, cellophane or long rice (mung beans), dehydrated"
  },
  "174272": {
    "kcal": 192,
    "protein": 20.3,
    "fat": 10.8,
    "carb": 7.64,
    "fiber": 0,
    "description": "Tempeh"
  },
  "174278": {
    "kcal": 60,
    "protein": 10.5,
    "fat": 0.1,
    "carb": 5.57,
    "fiber": 0.8,
    "description": "Soy sauce made from soy (tamari)"
  },
  "174280": {
    "kcal": 116,
    "protein": 8.92,
    "fat": 8,
    "carb": 4.38,
    "fiber": 0,
    "description": "Tofu, salted and fermented (fuyu)"
  },
  "174284": {
    "kcal": 358,
    "protein": 23.9,
    "fat": 2.17,
    "carb": 63.1,
    "fiber": 10.8,
    "description": "Lentils, pink or red, raw"
  },
  "174288": {
    "kcal": 387,
    "protein": 22.4,
    "fat": 6.69,
    "carb": 57.8,
    "fiber": 10.8,
    "description": "Chickpea flour (besan)"
  },
  "174289": {
    "kcal": 237,
    "protein": 7.78,
    "fat": 17.8,
    "carb": 15,
    "fiber": 5.5,
    "description": "Hummus, commercial"
  },
  "174301": {
    "kcal": 328,
    "protein": 63.6,
    "fat": 0.46,
    "carb": 25.4,
    "fiber": 5.5,
    "description": "Soy protein concentrate, produced by acid wash"
  },
  "174342": {
    "kcal": 206,
    "protein": 18.6,
    "fat": 14.5,
    "carb": 0.13,
    "fiber": 0,
    "description": "Lamb, New Zealand, imported, leg chop/steak, bone-in, separable lean and fat, raw"
  },
  "174442": {
    "kcal": 84,
    "protein": 15.2,
    "fat": 2.54,
    "carb": 0.03,
    "fiber": 0,
    "description": "Lamb, New Zealand, imported, kidney, raw"
  },
  "174528": {
    "kcal": 12,
    "protein": 1.29,
    "fat": 0.76,
    "carb": 0.8,
    "fiber": 0.6,
    "description": "Sauce, ready-to-serve, pepper, TABASCO"
  },
  "174529": {
    "kcal": 51,
    "protein": 1.35,
    "fat": 0.25,
    "carb": 10.9,
    "fiber": 0.3,
    "description": "Sauce, oyster, ready-to-serve"
  },
  "174531": {
    "kcal": 35,
    "protein": 5.06,
    "fat": 0.01,
    "carb": 3.64,
    "fiber": 0,
    "description": "Sauce, fish, ready-to-serve"
  },
  "174577": {
    "kcal": 326,
    "protein": 14.1,
    "fat": 28.7,
    "carb": 1.63,
    "fiber": 0,
    "description": "Polish sausage, pork"
  },
  "174584": {
    "kcal": 309,
    "protein": 12,
    "fat": 28.2,
    "carb": 0.94,
    "fiber": 0,
    "description": "Sausage, smoked link sausage, pork"
  },
  "174595": {
    "kcal": 341,
    "protein": 14,
    "fat": 31.7,
    "carb": 0,
    "fiber": 0,
    "description": "Bratwurst, veal, cooked"
  },
  "174611": {
    "kcal": 122,
    "protein": 17.9,
    "fat": 2.37,
    "carb": 7.27,
    "fiber": 0,
    "description": "Ham, honey, smoked, cooked"
  },
  "174619": {
    "kcal": 389,
    "protein": 3.41,
    "fat": 4.61,
    "carb": 86.8,
    "fiber": 3.3,
    "description": "Cereals ready-to-eat, MALT-O-MEAL, COCO-ROOS"
  },
  "174652": {
    "kcal": 397,
    "protein": 4.44,
    "fat": 4.83,
    "carb": 85.9,
    "fiber": 2.6,
    "description": "Cereals ready-to-eat, QUAKER, Christmas Crunch"
  },
  "174803": {
    "kcal": 383,
    "protein": 13.2,
    "fat": 10.5,
    "carb": 58.8,
    "fiber": 7.9,
    "description": "Snack, Mixed Berry Bar"
  },
  "174817": {
    "kcal": 231,
    "protein": 0,
    "fat": 0,
    "carb": 0,
    "fiber": 0,
    "description": "Alcoholic beverage, distilled, rum, 80 proof"
  },
  "174837": {
    "kcal": 82,
    "protein": 0.07,
    "fat": 0,
    "carb": 2.6,
    "fiber": 0,
    "description": "Alcoholic beverage, wine, table, white"
  },
  "174891": {
    "kcal": 538,
    "protein": 16.9,
    "fat": 52.3,
    "carb": 0,
    "fiber": 0,
    "description": "Lamb, Australian, imported, fresh, external fat, cooked"
  },
  "174896": {
    "kcal": 175,
    "protein": 22,
    "fat": 9.73,
    "carb": 0,
    "fiber": 0,
    "description": "Lamb, Australian, imported, fresh, leg, trotter off, bone-in, separable lean and fat, trimmed to 1/8\" fat, raw"
  },
  "174913": {
    "kcal": 259,
    "protein": 9.49,
    "fat": 2.73,
    "carb": 48.1,
    "fiber": 2.1,
    "description": "Bread, Italian"
  },
  "174915": {
    "kcal": 275,
    "protein": 9.1,
    "fat": 1.2,
    "carb": 55.7,
    "fiber": 2.2,
    "description": "Bread, pita, white, enriched"
  },
  "174952": {
    "kcal": 497,
    "protein": 4.6,
    "fat": 25.2,
    "carb": 66.1,
    "fiber": 0,
    "description": "Cookies, chocolate chip, dry mix"
  },
  "174965": {
    "kcal": 478,
    "protein": 8.8,
    "fat": 21.1,
    "carb": 65.6,
    "fiber": 1.9,
    "description": "Cookies, peanut butter sandwich, regular"
  },
  "174980": {
    "kcal": 446,
    "protein": 7.6,
    "fat": 13.8,
    "carb": 71.7,
    "fiber": 3.4,
    "description": "Crackers, milk"
  },
  "174988": {
    "kcal": 254,
    "protein": 7.4,
    "fat": 8.7,
    "carb": 37.1,
    "fiber": 2.5,
    "description": "Croissants, apple"
  },
  "175020": {
    "kcal": 224,
    "protein": 1.9,
    "fat": 10,
    "carb": 32.9,
    "fiber": 0.8,
    "description": "Pie, peach"
  },
  "175027": {
    "kcal": 307,
    "protein": 9.5,
    "fat": 6.4,
    "carb": 52,
    "fiber": 3.7,
    "description": "Rolls, dinner, egg"
  },
  "175028": {
    "kcal": 236,
    "protein": 9.5,
    "fat": 4.6,
    "carb": 40.2,
    "fiber": 4.1,
    "description": "Rolls, dinner, oat bran"
  },
  "175037": {
    "kcal": 306,
    "protein": 8.2,
    "fat": 7.99,
    "carb": 49.4,
    "fiber": 3.5,
    "description": "Tortillas, ready-to-bake or -fry, flour, refrigerated"
  },
  "175041": {
    "kcal": 258,
    "protein": 0,
    "fat": 0,
    "carb": 61.5,
    "fiber": 0.2,
    "description": "Leavening agents, cream of tartar"
  },
  "175083": {
    "kcal": 424,
    "protein": 6.99,
    "fat": 10,
    "carb": 76.2,
    "fiber": 3.4,
    "description": "Nabisco, Nabisco Grahams Crackers"
  },
  "175112": {
    "kcal": 152,
    "protein": 0.2,
    "fat": 0,
    "carb": 11.7,
    "fiber": 0,
    "description": "Alcoholic beverage, wine, dessert, dry"
  },
  "175138": {
    "kcal": 127,
    "protein": 20.5,
    "fat": 4.4,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, salmon, pink, raw"
  },
  "175139": {
    "kcal": 208,
    "protein": 24.6,
    "fat": 11.4,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, sardine, Atlantic, canned in oil, drained solids with bone"
  },
  "175142": {
    "kcal": 97,
    "protein": 18.4,
    "fat": 2,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, sea bass, mixed species, raw"
  },
  "175150": {
    "kcal": 92,
    "protein": 16.8,
    "fat": 2.32,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, sucker, white, raw"
  },
  "175153": {
    "kcal": 148,
    "protein": 20.8,
    "fat": 6.61,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, trout, mixed species, raw"
  },
  "175160": {
    "kcal": 187,
    "protein": 16,
    "fat": 9.26,
    "carb": 9.41,
    "fiber": 0,
    "description": "Fish, tuna salad"
  },
  "175180": {
    "kcal": 99,
    "protein": 24,
    "fat": 0.28,
    "carb": 0.2,
    "fiber": 0,
    "description": "Crustaceans, shrimp, cooked"
  },
  "175183": {
    "kcal": 121,
    "protein": 6.38,
    "fat": 3.45,
    "carb": 16.9,
    "fiber": 0,
    "description": "Beans, baked, canned, with beef"
  },
  "175196": {
    "kcal": 329,
    "protein": 25.3,
    "fat": 0.45,
    "carb": 58.3,
    "fiber": 24.9,
    "description": "Beans, kidney, royal red, mature seeds, raw"
  },
  "175262": {
    "kcal": 272,
    "protein": 16.2,
    "fat": 22.9,
    "carb": 0.24,
    "fiber": 0,
    "description": "Lamb, New Zealand, imported, square-cut shoulder, separable lean and fat, raw"
  },
  "175303": {
    "kcal": 109,
    "protein": 20.6,
    "fat": 2.31,
    "carb": 0,
    "fiber": 0,
    "description": "Game meat, goat, raw"
  },
  "321360": {
    "kcal": 27,
    "protein": 0.83,
    "fat": 0.63,
    "carb": 5.51,
    "fiber": 2.1,
    "description": "Tomatoes, grape, raw"
  },
  "323793": {
    "kcal": 376,
    "protein": 79.9,
    "fat": 0.65,
    "carb": 6.02,
    "fiber": 0,
    "description": "Egg, white, dried"
  },
  "324653": {
    "kcal": 12,
    "protein": 0.48,
    "fat": 0.43,
    "carb": 1.99,
    "fiber": 1,
    "description": "Pickles, cucumber, dill or kosher dill"
  },
  "328637": {
    "kcal": 408,
    "protein": 23.3,
    "fat": 34,
    "carb": 2.44,
    "fiber": 0,
    "description": "Cheese, cheddar"
  },
  "332791": {
    "kcal": 130,
    "protein": 1.15,
    "fat": 12.9,
    "carb": 4.96,
    "fiber": 4,
    "description": "Olives, green, Manzanilla, stuffed with pimiento"
  },
  "333374": {
    "kcal": 74,
    "protein": 16.3,
    "fat": 0.45,
    "carb": 0,
    "fiber": 0,
    "description": "Fish, haddock, raw"
  },
  "746766": {
    "kcal": 157,
    "protein": 7.81,
    "fat": 11,
    "carb": 6.86,
    "fiber": 0,
    "description": "Cheese, ricotta, whole milk"
  },
  "746767": {
    "kcal": 393,
    "protein": 27,
    "fat": 31,
    "carb": 1.44,
    "fiber": 0,
    "description": "Cheese, swiss"
  },
  "746784": {
    "kcal": 385,
    "protein": 0,
    "fat": 0.32,
    "carb": 99.6,
    "fiber": 0,
    "description": "Sugars, granulated"
  },
  "747441": {
    "kcal": 0,
    "protein": 24.1,
    "fat": 1.51,
    "carb": 0,
    "fiber": 4.3,
    "description": "Beans, Dry, Navy (0% moisture)"
  },
  "747445": {
    "kcal": 0,
    "protein": 23.7,
    "fat": 1.24,
    "carb": 0,
    "fiber": 4.1,
    "description": "Beans, Dry, Pinto (0% moisture)"
  },
  "747446": {
    "kcal": 0,
    "protein": 24.7,
    "fat": 1.24,
    "carb": 0,
    "fiber": 4.3,
    "description": "Beans, Dry, Great Northern (0% moisture)"
  },
  "747447": {
    "kcal": 31,
    "protein": 2.57,
    "fat": 0.34,
    "carb": 6.27,
    "fiber": 2.4,
    "description": "Broccoli, raw"
  },
  "747693": {
    "kcal": 117,
    "protein": 1.11,
    "fat": 0.55,
    "carb": 26.8,
    "fiber": 0,
    "description": "Ketchup, restaurant"
  },
  "747997": {
    "kcal": 55,
    "protein": 10.7,
    "fat": 0,
    "carb": 2.36,
    "fiber": 0,
    "description": "Eggs, Grade A, Large, egg white"
  },
  "789828": {
    "kcal": 0,
    "protein": 0,
    "fat": 81.5,
    "carb": 0,
    "fiber": 0,
    "description": "Butter, stick, unsalted"
  },
  "789890": {
    "kcal": 366,
    "protein": 10.9,
    "fat": 1.48,
    "carb": 77.3,
    "fiber": 0,
    "description": "Flour, wheat, all-purpose, enriched, bleached"
  },
  "790146": {
    "kcal": 363,
    "protein": 14.3,
    "fat": 1.65,
    "carb": 72.8,
    "fiber": 0,
    "description": "Flour, bread, white, enriched, unbleached"
  },
  "790214": {
    "kcal": 359,
    "protein": 6.94,
    "fat": 1.3,
    "carb": 79.8,
    "fiber": 0.5,
    "description": "Flour, rice, white, unenriched"
  },
  "790577": {
    "kcal": 44,
    "protein": 0.94,
    "fat": 0.1,
    "carb": 9.93,
    "fiber": 2.2,
    "description": "Onions, red, raw"
  },
  "1104647": {
    "kcal": 143,
    "protein": 6.62,
    "fat": 0.38,
    "carb": 28.2,
    "fiber": 2.7,
    "description": "Garlic, raw"
  },
  "1104812": {
    "kcal": 365,
    "protein": 7.19,
    "fat": 3.85,
    "carb": 75.5,
    "fiber": 0,
    "description": "Flour, rice, brown"
  },
  "1104867": {
    "kcal": 358,
    "protein": 6.69,
    "fat": 1.16,
    "carb": 80.1,
    "fiber": 0,
    "description": "Flour, rice, glutinous"
  },
  "1105314": {
    "kcal": 97,
    "protein": 0.74,
    "fat": 0.29,
    "carb": 23,
    "fiber": 1.7,
    "description": "Bananas, ripe and slightly ripe, raw"
  },
  "1999627": {
    "kcal": 0,
    "protein": 2.9,
    "fat": 0.188,
    "carb": 6.94,
    "fiber": 2.85,
    "description": "Mushroom, oyster"
  },
  "1999628": {
    "kcal": 0,
    "protein": 2.41,
    "fat": 0.195,
    "carb": 8.17,
    "fiber": 4.17,
    "description": "Mushrooms, shiitake"
  },
  "1999632": {
    "kcal": 0,
    "protein": 2.85,
    "fat": 0.619,
    "carb": 2.41,
    "fiber": 1.56,
    "description": "Spinach, baby"
  },
  "1999633": {
    "kcal": 0,
    "protein": 2.91,
    "fat": 0.604,
    "carb": 2.64,
    "fiber": 1.59,
    "description": "Spinach, mature"
  },
  "2003589": {
    "kcal": 0,
    "protein": 13.3,
    "fat": 1.84,
    "carb": 72,
    "fiber": 3.68,
    "description": "Flour, semolina, fine"
  },
  "2003603": {
    "kcal": 0,
    "protein": 2.18,
    "fat": 0.449,
    "carb": 6.76,
    "fiber": 3.14,
    "description": "Mushroom, beech"
  },
  "2258588": {
    "kcal": 0,
    "protein": 0.715,
    "fat": 0.106,
    "carb": 4.78,
    "fiber": 0.942,
    "description": "Peppers, bell, green, raw"
  },
  "2258589": {
    "kcal": 0,
    "protein": 0.819,
    "fat": 0.121,
    "carb": 6.6,
    "fiber": 1.07,
    "description": "Peppers, bell, yellow, raw"
  },
  "2258590": {
    "kcal": 0,
    "protein": 0.896,
    "fat": 0.126,
    "carb": 6.65,
    "fiber": 1.16,
    "description": "Peppers, bell, red, raw"
  },
  "2259792": {
    "kcal": 0,
    "protein": 3.46,
    "fat": 1.08,
    "carb": 4.81,
    "fiber": 0,
    "description": "Buttermilk, low fat"
  },
  "2261420": {
    "kcal": 0,
    "protein": 26.2,
    "fat": 50.2,
    "carb": 16.2,
    "fiber": 9.27,
    "description": "Flour, almond"
  },
  "2262072": {
    "kcal": 0,
    "protein": 24,
    "fat": 49.4,
    "carb": 22.7,
    "fiber": 6.32,
    "description": "Peanut butter, creamy"
  },
  "2346386": {
    "kcal": 0,
    "protein": 2.02,
    "fat": 35.6,
    "carb": 3.8,
    "fiber": 0,
    "description": "Cream, heavy"
  },
  "2346387": {
    "kcal": 0,
    "protein": 3.07,
    "fat": 18,
    "carb": 5.56,
    "fiber": 0,
    "description": "Cream, sour, full fat"
  },
  "2346388": {
    "kcal": 0,
    "protein": 0.742,
    "fat": 0.0738,
    "carb": 3.37,
    "fiber": 0,
    "description": "Lettuce, iceberg, raw"
  },
  "2346405": {
    "kcal": 0,
    "protein": 0.492,
    "fat": 0.162,
    "carb": 3.32,
    "fiber": 0,
    "description": "Celery, raw"
  },
  "2346410": {
    "kcal": 0,
    "protein": 1.01,
    "fat": 0.188,
    "carb": 12.9,
    "fiber": 0,
    "description": "Raspberries, raw"
  },
  "2346411": {
    "kcal": 0,
    "protein": 0.703,
    "fat": 0.306,
    "carb": 14.6,
    "fiber": 0,
    "description": "Blueberries, raw"
  },
  "2512374": {
    "kcal": 0,
    "protein": 8.88,
    "fat": 2.48,
    "carb": 75,
    "fiber": 10.4,
    "description": "Flour, buckwheat"
  },
  "2515374": {
    "kcal": 0,
    "protein": 17.4,
    "fat": 38.9,
    "carb": 36.3,
    "fiber": 4.1,
    "description": "Nuts, cashew nuts, raw"
  },
  "2515375": {
    "kcal": 0,
    "protein": 13.5,
    "fat": 53.5,
    "carb": 26.5,
    "fiber": 8.41,
    "description": "Nuts, hazelnuts or filberts, raw"
  },
  "2515376": {
    "kcal": 0,
    "protein": 23.2,
    "fat": 43.3,
    "carb": 26.5,
    "fiber": 8.01,
    "description": "Peanuts, raw"
  },
  "2515377": {
    "kcal": 0,
    "protein": 5.29,
    "fat": 4.64,
    "carb": 80.5,
    "fiber": 8.71,
    "description": "Flour, chestnut"
  },
  "2515382": {
    "kcal": 0,
    "protein": 16.1,
    "fat": 15.3,
    "carb": 58.9,
    "fiber": 34.2,
    "description": "Flour, coconut"
  },
  "2644281": {
    "kcal": 0,
    "protein": 21.6,
    "fat": 2.2,
    "carb": 59.8,
    "fiber": 0,
    "description": "Beans, cannellini, dry"
  },
  "2644283": {
    "kcal": 0,
    "protein": 23.6,
    "fat": 1.92,
    "carb": 62.2,
    "fiber": 0,
    "description": "Lentils, dry"
  },
  "2644284": {
    "kcal": 0,
    "protein": 21.2,
    "fat": 2.42,
    "carb": 61.8,
    "fiber": 0,
    "description": "Blackeye pea, dry"
  },
  "2644288": {
    "kcal": 0,
    "protein": 7.02,
    "fat": 3.1,
    "carb": 20.3,
    "fiber": 0,
    "description": "Chickpeas (garbanzo beans, bengal gram), canned, sodium added, drained and rinsed"
  },
  "2646169": {
    "kcal": 0,
    "protein": 21.6,
    "fat": 3.9,
    "carb": 0,
    "fiber": 0,
    "description": "Pork, loin, tenderloin, boneless, raw"
  },
  "2646174": {
    "kcal": 0,
    "protein": 18.4,
    "fat": 17.8,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, chuck, roast, boneless, choice, raw"
  },
  "2646175": {
    "kcal": 0,
    "protein": 20.1,
    "fat": 9.4,
    "carb": 0,
    "fiber": 0,
    "description": "Beef, flank, steak, boneless, choice, raw"
  },
  "2647438": {
    "kcal": 0,
    "protein": 22.6,
    "fat": 32.6,
    "carb": 1.9,
    "fiber": 0,
    "description": "Cheese, monterey jack, solid"
  },
  "2685572": {
    "kcal": 0,
    "protein": 1.02,
    "fat": 0.234,
    "carb": 3.51,
    "fiber": 1.26,
    "description": "Cabbage, bok choy, raw"
  },
  "2685575": {
    "kcal": 0,
    "protein": 3.98,
    "fat": 0.565,
    "carb": 9.62,
    "fiber": 4.78,
    "description": "Brussels sprouts, raw"
  },
  "2685576": {
    "kcal": 0,
    "protein": 1.69,
    "fat": 0.302,
    "carb": 8.79,
    "fiber": 3.12,
    "description": "Beets, raw"
  },
  "2685582": {
    "kcal": 0,
    "protein": 1.58,
    "fat": 0.265,
    "carb": 8.04,
    "fiber": 1.97,
    "description": "Tomato, puree, canned"
  },
  "2710823": {
    "kcal": 0,
    "protein": 1.44,
    "fat": 0.216,
    "carb": 5.1,
    "fiber": 1.88,
    "description": "Asparagus, green, raw"
  },
  "2727566": {
    "kcal": 0,
    "protein": 18.4,
    "fat": 5.94,
    "carb": -0.475,
    "fiber": 0,
    "description": "Chicken, drumstick, meat and skin, raw"
  },
  "2727568": {
    "kcal": 0,
    "protein": 18.4,
    "fat": 10.6,
    "carb": -0.459,
    "fiber": 0,
    "description": "Chicken, wing, meat and skin, raw"
  },
  "2727573": {
    "kcal": 0,
    "protein": 21.1,
    "fat": 6.46,
    "carb": 0.18,
    "fiber": 0,
    "description": "Beef, tenderloin steak, raw"
  },
  "2727575": {
    "kcal": 0,
    "protein": 22.8,
    "fat": 5.48,
    "carb": -0.562,
    "fiber": 0,
    "description": "Pork, chop, center cut, raw"
  },
  "2727576": {
    "kcal": 0,
    "protein": 15.2,
    "fat": 35.8,
    "carb": -0.705,
    "fiber": 0,
    "description": "Pork, belly, with skin, raw"
  },
  "2747655": {
    "kcal": 0,
    "protein": 0.922,
    "fat": 0.14,
    "carb": 5.49,
    "fiber": 2.05,
    "description": "Fennel, bulb, raw"
  },
  "2747669": {
    "kcal": 0,
    "protein": 20.7,
    "fat": 0.569,
    "carb": 0.441,
    "fiber": 0,
    "description": "Snapper, frozen, wild caught"
  },
  "2747670": {
    "kcal": 0,
    "protein": 15.5,
    "fat": 0.294,
    "carb": 1.11,
    "fiber": 0,
    "description": "Snow crab, legs only, frozen  "
  }
};
